export const en = {
  languageName: 'English',
  languageChinese: '中文',
  languageEnglish: 'English',
  settings: 'Settings',
  close: 'Close',
  back: 'Back',
  search: 'Search',
  selectedTags: 'Selected tags',
  searchSelectedTags: 'Search selected tags',
  unknown: 'Unknown',
  noCover: 'No cover',
  loading: 'Loading...',
  noResults: 'No results',
  homeTitle: 'Steam Workshop Wallpapers',
  homeApprox: 'About',
  homeItems: 'items',
  homePagesPrefix: '',
  homePagesSuffix: 'pages',
  searchHint: 'Search wallpaper name, project ID, or author ID: author:114514',
  exactPhrase: 'Exact phrase',
  themeToggle: 'Toggle theme',
  themeMode: 'Display mode',
  themeModeDesc: 'System is the default. You can also force light or dark mode.',
  themeSystem: 'Follow system',
  themeLight: 'Light mode',
  themeDark: 'Dark mode',
  queue: 'Download queue',
  sortBy: 'Sort by',
  sortTrend: 'Trending',
  sortRecent: 'Recent',
  sortTopRated: 'Top rated',
  sortVotes: 'Most voted',
  sortSubscribers: 'Most subscribed',
  sortPersonalSubscriptions: 'My subscriptions',
  sortMyFavorites: 'My favorites',
  sortVoted: 'Voted items',
  sortFriendsFavorites: 'Friends favorites',
  sortFriendsCreated: 'Friends created',
  sortFollowedCreated: 'Followed authors',
  timeSort: 'Time range',
  personalSortSubscriptionDate: 'Subscription date',
  personalSortAlphabetical: 'Alphabetical',
  personalSortLastUpdated: 'Update date',
  personalSortCreationDate: 'Creation date',
  today: 'Today',
  week: 'Week',
  month: 'Month',
  threeMonths: '3 months',
  halfYear: '6 months',
  year: 'Year',
  allTime: 'All time',
  typeSelect: 'Type',
  homeFilterMultiSelect: 'Multi-select home filters',
  homeFilterMultiSelectDesc: 'Enable multi-select for type and age rating filters. Disable it to use single-select mode.',
  all: 'All',
  scene: 'Scene',
  video: 'Video',
  web: 'Web',
  application: 'Application',
  ageRating: 'Age rating',
  ratingEveryone: 'Everyone',
  ratingQuestionable: 'Questionable',
  ratingMature: 'Mature',
  filter: 'Filter',
  filterAllShort: 'All',
  grid: 'Grid',
  list: 'List',
  untitledWallpaper: 'Untitled wallpaper',
  subscribe: 'Subscribe',
  subscribeOpen: 'Open subscription',
  clientPreparing: 'Preparing client download...',
  clientSent: 'Download sent to browser',
  normalDownload: 'Download now',
  downloadStartTitle: 'Choose download method',
  downloadPkgSource: 'Download ZIP archive',
  downloadDesktopFormat: '(desktop format)',
  downloadMpkgMobile: 'Download MPKG file',
  downloadMobileFormat: '(mobile format)',
  mpkgConvertOnly: 'Convert MPKG only',
  downloadChoiceTitle: 'Choose download format',
  copied: 'Copied',
  copyTitle: 'Copy title',
  mpkgConvertDownload: 'Convert MPKG and download',
  mpkgPreparingStart: 'Preparing MPKG...',
  mpkgSent: 'MPKG sent to browser',
  mpkgConvertOnlyPreparing: 'Converting MPKG and keeping it in the project folder...',
  mpkgConvertOnlySourceDownloadingProgress: 'Downloading the wallpaper source — waiting {seconds}s. The MPKG will be converted and retained when the download is complete.',
  mpkgConvertOnlyPreparingProgress: 'Converting MPKG — waiting {seconds}s. The result will remain in the project Mpkg folder.',
  mpkgConvertOnlyReady: 'MPKG converted and saved in the project Mpkg folder',
  queuedDownload: 'Added to background download queue',
  downloadCompleted: 'Download completed: {title}',
  videoPlayer: 'Video player',
  videoQueued: 'Video was added to the preparation queue. Check progress in the download queue.',
  videoLoading: 'Loading video...',
  videoPreparing: 'Downloading and preparing video playback',
  videoPlayerControls: 'Video player controls',
  videoPlayerControlsDesc: 'Default mode uses the browser controls. Compatibility mode uses WallHub controls for Edge and some Android WebView versions.',
  videoPlayerModeDefault: 'Default mode',
  videoPlayerModeCompatibility: 'Compatibility mode',
  videoPlay: 'Play',
  videoPause: 'Pause',
  videoMute: 'Mute',
  videoUnmute: 'Unmute',
  videoSeek: 'Playback position',
  videoVolume: 'Volume',
  videoPlaybackRate: 'Playback speed',
  videoEnterFullscreen: 'Enter fullscreen',
  videoExitFullscreen: 'Exit fullscreen',
  videoShortcutsLabel: 'Player shortcuts',
  videoShortcutPlayPause: 'Play / pause',
  videoShortcutBack5: 'Back 5s',
  videoShortcutForward5: 'Forward 5s',
  videoShortcutHold: 'Hold',
  videoShortcutSpeed: '2x playback',
  videoShortcutFullscreen: 'Fullscreen',
  videoShortcutExitFullscreen: 'Exit fullscreen',
  videoSpeedPlaying: 'Playing at 2x speed…',
  settingsSaved: 'Settings saved',
  saveApply: 'Save and apply',
  deleted: 'Deleted',
  loginRequired: 'Please log in with a Steam account that owns Wallpaper Engine before continuing',
  loggedOut: 'Logged out',
  restartingServer: 'Server is restarting',
  shutdownConfirm: 'Shut down the server? You will need to start it again from the terminal.',
  shuttingDownServer: 'Server is shutting down',
  loginSuccess: 'Login successful',
  navServer: 'Server',
  navDownload: 'Downloads',
  navSteam: 'Steam settings',
  navAppearance: 'Appearance',
  navExperimental: 'Experimental',
  serverIntro: 'Runtime mode, folders, and server process controls.',
  runMode: 'Runtime mode',
  runStatus: 'Runtime status',
  contentMode: 'Content mode',
  currentCdnNode: 'Current CDN node',
  cdnWaiting: 'Waiting for download connection',
  currentDohServer: 'DoH resolver',
  currentResolverServer: 'Resolver',
  webapiConnectionStatus: 'WebAPI connection',
  webapiConnectionIdle: 'Waiting for WebAPI connection',
  webapiConnectionError: 'Last error',
  dohWaiting: 'Waiting for DoH resolution',
  resolverWaiting: 'Waiting for resolution',
  safeMode: 'Safe',
  runnerDir: 'Runner folder',
  downloadsDir: 'Download folder',
  serverControl: 'Server control',
  restartServer: 'Restart server',
  shutdownServer: 'Shut down server',
  appUpdate: 'Application update',
  currentVersion: 'Current version',
  latestVersion: 'Latest version',
  updateStatus: 'Update status',
  updateStatusIdle: 'Not checked yet',
  updateStatusChecking: 'Checking for updates',
  updateStatusCurrent: 'Up to date',
  updateStatusAvailable: 'New version available',
  updateStatusUnsupported: 'No update package is available for this installation',
  updateStatusDownloading: 'Downloading and verifying update',
  updateStatusDownloaded: 'Update package is ready',
  updateStatusInstalling: 'Installing and restarting',
  updateStatusError: 'Update failed',
  checkUpdate: 'Check for updates',
  downloadUpdate: 'Download update',
  installUpdate: 'Install and restart',
  viewRelease: 'View release',
  autoUpdate: 'Automatic updates',
  autoUpdateDesc: 'Download and verify new releases automatically, then install when no download tasks are active. Updating restarts WallHub.',
  updateAvailableToast: 'WallHub v{version} is available',
  updateDownloadStarted: 'Update download started',
  updateInstallConfirm: 'Install the update and restart WallHub? Make sure no important operation is in progress.',
  updateCheckFailed: 'Could not check for updates',
  updateDownloadFailed: 'Could not download or verify the update',
  updateInstallFailed: 'Could not install the update',
  dockerUpdateManaged: 'A separate container manages Docker updates. WallHub itself never accesses the Docker socket.',
  dockerUpdateManual: 'Pull the new image and recreate the container, or enable the Compose auto-update profile.',
  downloadIntro: 'Adjust the download folder and background download concurrency.',
  downloadDir: 'Download folder',
  saveDir: 'Save folder',
  mpkgTextureProfile: 'MPKG conversion mode',
  mpkgTextureProfileDesc: 'Choose whether conversion prioritizes speed or compression: Fast mode finishes sooner; Maximum compression makes a smaller MPKG file but takes longer. If maximum compression is unavailable, WallHub uses Fast mode automatically.',
  mpkgTextureProfileFast: 'Fast mode',
  mpkgTextureProfileCompact: 'Maximum compression',
  mpkgTextureProfileCompactUnavailable: 'Maximum compression is unavailable here, so WallHub will use Fast mode.',
  maxConcurrentDownloads: 'Max concurrent downloads',
  steamCdnRoute: 'HTTP(S)/SOCKS5 proxy',
  steamCdnRouteDesc: 'Enter an HTTP(S)/SOCKS5 proxy URL for SteamKit downloads and chunk streaming. Leave empty to use the default system network.',
  steamCdnRouteStrategy: 'HTTP(S)/SOCKS5 proxy URL',
  steamCdnNearest: 'Default system network',
  steamCdnNearestDesc: 'Downloader processes use the default system network environment.',
  steamCdnDirect: 'Default system network',
  steamCdnDirectDesc: 'Downloader processes use the default system network environment.',
  steamCdnProxy: 'HTTP(S)/SOCKS5 proxy',
  steamCdnProxyDesc: 'Download traffic uses the configured HTTP(S)/SOCKS5 proxy. CDN may be chosen near that proxy endpoint.',
  steamCdnNearestShort: 'Default network',
  steamCdnDefaultShort: 'Default network',
  steamCdnDirectShort: 'Default network',
  steamCdnProxyShort: 'Custom proxy',
  steamHttpProxyUrl: 'HTTP(S)/SOCKS5 proxy URL',
  steamHttpProxyPlaceholder: 'http://127.0.0.1:7890 or socks5://127.0.0.1:7890',
  saveCdnRoute: 'Save proxy settings',
  steamKitMaxDownloads: 'SteamKit per-item concurrency',
  steamKitMaxDownloadsDesc: 'Controls DepotDownloader -max-downloads. Auto uses 24 on Windows, 16 on Linux, and 12 on Termux.',
  depotStreamCacheMax: 'Streaming cache limit',
  depotStreamCacheMaxDesc: 'Limits SteamKit chunk-stream cache usage. Completed downloads are not affected.',
  depotStreamCacheCustom: 'Custom cache limit',
  depotStreamCacheCustomPlaceholder: 'Enter MB, for example 512 or 4096',
  clearDepotStreamCache: 'Clear cache now',
  depotStreamCacheCleared: 'Streaming cache cleared',
  effectiveValue: 'Effective',
  itemUnit: 'items',
  current: 'Current',
  defaultMark: 'default',
  steamIntro: 'Login status and SteamKit Workshop access.',
  accountStatus: 'Account status',
  loggedInAs: 'Logged in',
  steamUser: 'Steam user',
  currentNotLoggedIn: 'Not logged in',
  steamNotLoggedInDownloadHint: 'You are not logged in with a Steam account that owns Wallpaper Engine, so you cannot download | play Wallpaper items',
  logout: 'Log out',
  loginSteam: 'Log in to Steam',
  steamApiTitle: 'Steam Web API',
  steamApiPlaceholder: 'Enter Steam Web API key',
  steamApiHelp: 'Steam Web API list queries require a valid API key. Missing or invalid keys and request failures report an error instead of falling back to Community. Direct item IDs use the public details endpoint.',
  steamApiQuery: 'Get a Steam Web API key',
  steamDataSourceTitle: 'Workshop data source',
  steamDataSourceLabel: 'Preferred data source',
  steamDataSourceHelp: 'Choose a fixed source for Workshop lists. Community uses the current Web session after login and queries anonymously when logged out. Web API requires a valid key, and CM requires a usable SteamKit session. Source failures do not switch automatically.',
  experimentalIntro: 'Experimental options are off by default and are used to test new playback and downloader strategies. Unavailable paths fall back to stable behavior.',
  steamKitDepotStreaming: 'SteamKit chunk streaming',
  steamKitDepotStreamingDesc: 'Experimental: try on-demand Steam depot/chunk streaming for video playback. It follows the HTTP(S)/SOCKS5 proxy setting and SteamKit per-item concurrency settings.',
  prefetchNextPage: 'Preload next page',
  prefetchNextPageDesc: 'When enabled, fetch and cache the following page after the current page loads. Turning it off immediately cancels an unfinished preload. Note: this adds network and device work, so it can increase loading pressure on slower connections or devices.',
  wallhubSteamAccessEnhance: 'Steam enhanced access',
  wallhubSteamAccessEnhanceDesc: 'When enabled, WallHub only exposes two modes: Smart Resolver and Hosts. Smart Resolver combines DoH/DoT with dynamic reachable nodes, while Hosts mode only uses your provided or auto-updated hosts mappings.',
  wallhubSteamAccessVerboseLogs: 'Verbose Steam access logs',
  wallhubSteamAccessVerboseLogsDesc: 'Troubleshooting switch: log resolver, probe and request attempts with host, IP, SNI, protocol, status and elapsed time on the server. Keep it off for normal use.',
  wallhubLogLevel: 'Server log level',
  wallhubLogLevelDesc: 'INFO logs key state only; DEBUG enables detailed Steam network, frontend click, and connection-layer logs on the server.',
  wallhubSteamAccessStaticCdnControl: 'Steam image and static asset domain controls',
  wallhubSteamAccessStaticCdnControlDesc: 'Control connection handling and reuse for the two Steam image and static asset domains: images.steamusercontent.com and shared.akamai.steamstatic.com.',
  wallhubSteamAccessStaticCdnHostDesc: 'Built-in enhancement uses WallHub connection optimization for this domain. Turning reuse off creates a fresh connection for every request, which can help when images or assets fail to load.',
  builtinEnhance: 'Built-in enhance',
  reuseConnection: 'Reuse connection',
  wallhubSteamWebApiControl: 'Steam WebAPI Control',
  wallhubSteamWebApiControlDesc: 'Customize api.steampowered.com connection strategy: route directly or follow resolver/hosts, and use HTTP or HTTPS.',
  wallhubSteamWebApiRouteLabel: 'Connection route',
  wallhubSteamWebApiRouteDirect: 'Direct',
  wallhubSteamWebApiRouteFollow: 'Follow resolver & hosts',
  wallhubSteamWebApiProtocolLabel: 'Protocol',
  wallhubSteamWebApiHostLabel: 'API host',
  steamCdnLockedByAccessEnhance: 'Steam enhanced access does not lock the HTTP(S)/SOCKS5 proxy setting.',
  dohPickerTitle: 'Resolver selection',
  dohSelectDesc: 'Choose DoH or DoT to resolve Steam domain IPs.',
  dohCurrent: 'Current resolver',
  dohModeFastest: 'Fastest response',
  dohModeFixed: 'Fixed resolver',
  dohSwitch: 'Change',
  dohSave: 'Save resolver',
  resolverPickerTitle: 'Connection mode',
  resolverSelectDesc: 'Switch between Smart Resolver and Hosts. Smart Resolver is best for automatic recovery from DNS pollution, while Hosts is best when you want fixed mappings.',
  resolverModeResolver: 'Smart Resolver',
  resolverModeHosts: 'Hosts mode',
  resolverSelectedCount: 'Selected resolvers',
  resolverCustomEndpoint: 'Custom',
  resolverHostsTitle: 'Hosts mode',
  resolverHostsDesc: 'Hosts mode only uses the persisted local hosts mapping. Missing hosts fall back to the normal access path and do not silently call DoH/DoT.',
  resolverHostsPlaceholder: '此处可以参考https://github.com/gagadog/steam_hosts',
  resolverHostsImport: 'Save hosts',
  resolverHostsFetch: 'Import/refresh',
  resolverHostsUrlPlaceholder: 'https://gh-proxy.org/https://raw.githubusercontent.com/ChEnLeo-7/Github_hosts/refs/heads/main/steam-hosts',
  resolverHostsUrlExample: 'Example URL',
  resolverHostsForkHint: 'You can also fork the Github_hosts repository and maintain a Hosts file resolved for your own region.',
  resolverHostsAutoUpdate: 'Auto-update hosts (hours)',
  resolverHostsLastUpdated: 'Last updated',
  resolverHostsLastError: 'Last error',
  resolverProtocolDoh: 'DoH',
  resolverProtocolDot: 'DoT',
  resolverCurrent: 'Current route',
  resolverModeFastest: 'Fastest response',
  resolverModeFixed: 'Fixed resolver',
  resolverSwitch: 'Manage',
  resolverSave: 'Add resolver',
  steamProxyQuickOpen: 'Open Steam URL through proxy',
  steamProxyQuickOpenDesc: 'Enter a Steam URL and open it through the Wallhub proxy entry. Useful when Steam pages need the built-in connection enhancement.',
  steamProxyQuickOpenPlaceholder: 'https://steamcommunity.com/ or https://store.steampowered.com/',
  steamProxyQuickCommunity: 'Steam Community',
  steamProxyQuickStore: 'Steam Store',
  steamProxyQuickWorkshop: 'Wallpaper Workshop',
  steamProxyQuickCharts: 'Steam charts',
  openProxyUrl: 'Open proxy',
  appearanceIntro: 'Adjust home page density and interface language.',
  language: 'Language',
  languageDesc: 'Switch the frontend display language.',
  accentTheme: 'Theme color',
  accentThemeDesc: 'Switch Monet-style accent colors. Default keeps the black and white mode.',
  accentMono: 'Default mono',
  accentBlue: 'Monet blue',
  accentGreen: 'Monet green',
  accentRose: 'Monet rose',
  accentViolet: 'Monet violet',
  accentCustom: 'Custom',
  customAccentColor: 'Custom theme color',
  fixedPanelHeight: 'Fixed panel height',
  fixedPanelHeightDesc: 'When enabled, secondary panels such as Settings, Queue, Details, and Login use a fixed height and scroll internally.',
  detailsPresentation: 'Details page style',
  detailsPresentationDesc: 'Switch between the original detail layout and the redesigned focused layout.',
  detailsPresentationClassic: 'Classic (original)',
  detailsPresentationRedesigned: 'Redesigned focused layout',
  homePageSize: 'Home cards per page',
  homePageSizeDesc: 'Controls how many cards Wallhub loads and paginates on the home page.',
  homeCardDefaultAction: 'Home card default button',
  homeCardDefaultActionDesc: 'Choose the default action for the button at the bottom of wallpaper cards.',
  actionPlayVideo: 'Play video',
  actionBackgroundDownload: 'Background download',
  actionClientDownload: 'Download locally',
  actionOpenSteamPage: 'Open Steam page',
  remoteSubscribePreparing: 'Sending the subscription request to Steam...',
  remoteSubscribeSuccess: 'Request sent! Check Personal Subscriptions or Wallpaper Engine on your computer',
  remoteSubscribePending: 'Subscribing{dots}',
  remoteSubscriptionActive: 'Subscribed',
  actionUnsubscribe: 'Unsubscribe',
  remoteUnsubscribePreparing: 'Sending the unsubscribe request to Steam...',
  remoteUnsubscribeSuccess: 'Unsubscribe request sent! Refresh Personal Subscriptions to check the result.',
  actionSubscribe: 'Subscribe',
  remoteFavoritePreparing: 'Sending the favorite request to Steam...',
  remoteFavoriteSuccess: 'Favorite request sent! Check My Favorites to see it.',
  remoteFavoritePending: 'Saving favorite{dots}',
  remoteFavoriteActive: 'Favorited',
  actionFavorite: 'Favorite',
  remoteUnfavoritePreparing: 'Sending the remove-favorite request to Steam...',
  remoteUnfavoriteSuccess: 'Remove-favorite request sent! Refresh My Favorites to check the result.',
  actionUnfavorite: 'Remove favorite',
  mobileColumns: 'Mobile home columns',
  desktopColumns: 'Desktop home columns',
  autoFit: 'Auto fit',
  auto: 'Auto',
  enabled: 'Enabled',
  disabled: 'Disabled',
  runtimeReady: 'runtime files ready',
  runtimeReadyJson: 'JSON progress downloader ready',
  runtimeCheckSteamKit: 'Checking SteamKit runtime files',
  runtimeBuildSteamKit: 'Building SteamKit JSON progress downloader',
  runtimeRelogin: 'Please log in to Steam again',
  runtimeLoginRestored: 'restored login',
  runtimeLoginKept: 'kept login',
  runtimeSessionUnverified: 'local login session is not verified, please log in again',
  runtimePrepareFailed: 'runtime preparation failed',
  runtimeBuildFailed: 'SteamKit JSON progress downloader build failed',
  queueEmpty: 'The queue is empty',
  queueStatusFilter: 'Download queue status filters',
  queueTypeFilter: 'Download queue wallpaper type filters',
  queueFilterModeSwitch: 'Switch between status and wallpaper type filters',
  queueFilterAll: 'All',
  queueFilterVideo: 'Video',
  queueFilterScene: 'Scene',
  queueFilterWeb: 'Web',
  queueFilterCompleted: 'Completed',
  queueFilterDownloading: 'Downloading',
  queueFilterPending: 'Queued',
  queueFilterFailed: 'Failed',
  queueFilteredEmpty: 'No tasks match the selected statuses',
  resumeAll: 'Resume all',
  pauseAll: 'Pause all',
  clearCompletedFailed: 'Clear completed and failed',
  waitingRealProgress: 'Downloading, waiting for downloader progress',
  waitingProgress: 'Waiting for progress',
  sizeUnknown: 'Size unknown',
  play: 'Play',
  download: 'Download',
  pause: 'Pause',
  resume: 'Resume',
  moveUp: 'Move up',
  moveDown: 'Move down',
  delete: 'Delete',
  statusPending: 'Queued',
  statusDownloading: 'Downloading',
  statusMoving: 'Moving',
  statusPaused: 'Paused',
  statusError: 'Failed',
  statusCompleted: 'Completed',
  author: 'Author',
  loadingAuthor: 'Loading',
  playVideo: 'Play video',
  backgroundDownload: 'Background download',
  downloadLocal: 'Download locally',
  openSteamPage: 'Open Steam page',
  subscriptions: 'Subscriptions',
  favorites: 'Favorites',
  views: 'Views',
  fileSize: 'File size',
  lastUpdated: 'Last updated',
  type: 'Type',
  loadingDescription: 'Loading description...',
  noDescription: 'No description',
  comments: 'Comments',
  loadingComments: 'Loading comments...',
  noComments: 'No comments',
  genreFilterTitle: 'Genre filter',
  genreTabGenres: 'Genres',
  genreTabOfficial: 'Official filters',
  genreTabResolution: 'Resolution',
  genreActiveFilters: 'Selected filters',
  clear: 'Clear',
  selectAll: 'Select all',
  applyFilter: 'Apply filters',
  steamLoginTitle: 'Steam account login',
  cancel: 'Cancel',
  cancelQr: 'Cancel QR',
  generateQr: 'Generate QR',
  submitGuard: 'Submit code',
  submitSteamToken: 'Log in with token',
  login: 'Log in',
  passwordLogin: 'Password',
  qrLogin: 'QR login',
  qrHelp: 'Scan the QR code with the Steam mobile app. DepotDownloader will save the local session after login succeeds.',
  passwordHelp: 'DepotDownloader verifies the Steam account and saves a local session. The password is not stored.',
  steamUsername: 'Steam username',
  steamPassword: 'Steam password',
  steamGuard: 'Steam Guard code',
  useSteamToken: 'Use Steam token',
  steamTokenCode: 'Steam token code',
  steamTokenHelp: 'Enter the code from Steam Mobile Authenticator to verify directly instead of waiting for email or phone approval.',
  enterSteamToken: 'Enter a Steam token code',
  qrGenerating: 'Generating QR code',
  qrStart: 'Generate a QR code to start login',
  qrWaitImage: 'Generating a scannable QR code...',
  qrWaitingOutput: 'Waiting for DepotDownloader QR output...',
  qrWillShow: 'The QR code will appear here',
  qrConfirmed: 'Confirmed account',
  qrFailed: 'QR login failed',
  enterCredentials: 'Enter username and password',
  guardRequired: 'Steam Guard code required',
  loginFailed: 'Login failed',
  loginStatus: 'Current login status',
  loginStarting: 'Starting login verification',
  phoneConfirmationRequired: 'Confirm this login in the Steam mobile app, then check your phone.',
  prevPage: 'Previous',
  nextPage: 'Next',
  backToTop: 'Back to top',
  loadingWorkshop: 'Fetching Steam Workshop...',
  warmingSteamIp: '正在预热SteamIP……',
  emptyWorkshop: 'No matching wallpapers. Try changing the filters.',
  networkHint: 'The current network may not be able to reach Steam Community. If a proxy is required, make sure the server process can read HTTP_PROXY / HTTPS_PROXY.',
  retry: 'Retry',
  copyProxyDomains: 'Copy proxy domains',
  genres: {
    Abstract: 'Abstract',
    Animal: 'Animal',
    Anime: 'Anime',
    Cartoon: 'Cartoon',
    CGI: 'CGI',
    Cyberpunk: 'Cyberpunk',
    Fantasy: 'Fantasy',
    Game: 'Game',
    Girls: 'Girls',
    Guys: 'Guys',
    Landscape: 'Landscape',
    Medieval: 'Medieval',
    Memes: 'Memes',
    MMD: 'MMD',
    Music: 'Music',
    Nature: 'Nature',
    'Pixel art': 'Pixel art',
    Relaxing: 'Relaxing',
    Retro: 'Retro',
    'Sci-Fi': 'Sci-Fi',
    Sports: 'Sports',
    Technology: 'Technology',
    Television: 'Television',
    Vehicle: 'Vehicle',
    Unspecified: 'Unspecified',
  },
} as const;
