export const zh = {
  languageName: '中文',
  languageChinese: '中文',
  languageEnglish: 'English',
  settings: '设置',
  close: '关闭',
  back: '返回',
  search: '搜索',
  selectedTags: '已选标签',
  searchSelectedTags: '搜索所选标签',
  unknown: '未知',
  noCover: '无封面',
  loading: '正在加载...',
  noResults: '暂无结果',
  homeTitle: 'Steam 创意工坊壁纸',
  homeApprox: '约',
  homeItems: '项',
  homePagesPrefix: '共',
  homePagesSuffix: '页',
  searchHint: '搜索壁纸名称、项目ID 或作者ID：author:114514',
  exactPhrase: '精确匹配短语',
  themeToggle: '切换主题',
  themeMode: '显示模式',
  themeModeDesc: '跟随系统为默认；也可以固定日间或夜间模式。',
  themeSystem: '跟随系统',
  themeLight: '日间模式',
  themeDark: '夜间模式',
  queue: '下载队列',
  sortBy: '排序依据',
  sortTrend: '最热门',
  sortRecent: '最近',
  sortTopRated: '评分最高',
  sortVotes: '最多投票',
  sortSubscribers: '最多订阅',
  sortPersonalSubscriptions: '个人订阅',
  sortMyFavorites: '我的收藏',
  sortVoted: '已投票',
  sortFriendsFavorites: '好友收藏',
  sortFriendsCreated: '好友创建',
  sortFollowedCreated: '关注者创建',
  timeSort: '时间排序',
  personalSortSubscriptionDate: '订阅日期',
  personalSortAlphabetical: '依字母顺序',
  personalSortLastUpdated: '更新日期',
  personalSortCreationDate: '创建日期',
  today: '今天',
  week: '一周',
  month: '一个月',
  threeMonths: '三个月',
  halfYear: '半年',
  year: '一年',
  allTime: '有史以来',
  typeSelect: '类型选择',
  homeFilterMultiSelect: '首页筛选多选',
  homeFilterMultiSelectDesc: '开启后类型和年龄评级可多选；关闭后恢复单选。',
  all: '全部',
  scene: '场景',
  video: '视频',
  web: '网页',
  application: '应用',
  ageRating: '年龄评级',
  ratingEveryone: '大众级',
  ratingQuestionable: '家长指导级',
  ratingMature: '限制成人级',
  filter: '筛选',
  filterAllShort: '全',
  grid: '网格',
  list: '列表',
  untitledWallpaper: '未命名壁纸',
  subscribe: '订阅',
  subscribeOpen: '打开订阅',
  clientPreparing: '正在准备客户端下载...',
  clientSent: '下载已发送到浏览器',
  normalDownload: '正常下载',
  downloadStartTitle: '选择下载方式',
  downloadPkgSource: '下载ZIP压缩包',
  downloadDesktopFormat: '（桌面端格式）',
  downloadMpkgMobile: '下载MPKG文件',
  downloadMobileFormat: '（移动端格式）',
  mpkgConvertOnly: '仅转换MPKG文件',
  downloadChoiceTitle: '选择下载格式',
  copied: '已复制',
  copyTitle: '复制标题',
  mpkgConvertDownload: 'Mpkg转换并下载',
  mpkgPreparingStart: '正在准备 MPKG...',
  mpkgSent: 'MPKG 已发送到浏览器',
  mpkgConvertOnlyPreparing: '正在转换 MPKG，仅保留到项目文件夹...',
  mpkgConvertOnlySourceDownloadingProgress: '正在下载壁纸源文件，已等待 {seconds} 秒；下载完成后将转换并保留 MPKG',
  mpkgConvertOnlyPreparingProgress: '正在转换 MPKG，已等待 {seconds} 秒；完成后将保留在项目 Mpkg 文件夹',
  mpkgConvertOnlyReady: 'MPKG 已转换并保存到项目 Mpkg 文件夹',
  queuedDownload: '已加入后台下载队列',
  downloadCompleted: '{title} 下载完成',
  videoPlayer: '视频播放',
  videoQueued: '视频已加入准备队列，请在下载队列查看进度',
  videoLoading: '视频正在加载...',
  videoPreparing: '视频正在下载并准备播放',
  videoPlayerControls: '视频播放器控件',
  videoPlayerControlsDesc: '默认模式使用浏览器原生控制栏；兼容模式使用 WallHub 控制栏，适用于 Edge 和部分 Android WebView。',
  videoPlayerModeDefault: '默认模式',
  videoPlayerModeCompatibility: '兼容模式',
  videoPlay: '播放',
  videoPause: '暂停',
  videoMute: '静音',
  videoUnmute: '取消静音',
  videoSeek: '播放进度',
  videoVolume: '音量',
  videoPlaybackRate: '播放速度',
  videoEnterFullscreen: '进入全屏',
  videoExitFullscreen: '退出全屏',
  videoShortcutsLabel: '播放器快捷键',
  videoShortcutPlayPause: '播放 / 暂停',
  videoShortcutBack5: '后退 5 秒',
  videoShortcutForward5: '快进 5 秒',
  videoShortcutHold: '长按',
  videoShortcutSpeed: '2x 倍速播放',
  videoShortcutFullscreen: '全屏',
  videoShortcutExitFullscreen: '退出全屏',
  videoSpeedPlaying: '正在以 2x倍速播放……',
  settingsSaved: '设置已保存',
  saveApply: '保存并应用',
  deleted: '已删除',
  loginRequired: '需要登录拥有 Wallpaper Engine 的 Steam 账号后再继续',
  loggedOut: '已退出登录',
  restartingServer: '服务端正在重启',
  shutdownConfirm: '确定要关闭服务端吗？关闭后需要在终端重新启动。',
  shuttingDownServer: '服务端正在关闭',
  loginSuccess: '登录成功',
  navServer: '服务端',
  navDownload: '下载设置',
  navSteam: 'Steam相关设置',
  navAppearance: '外观',
  navExperimental: '实验性',
  serverIntro: '运行方式、目录和服务进程控制。',
  runMode: '运行模式',
  runStatus: '运行状态',
  contentMode: '内容模式',
  currentCdnNode: '当前 CDN 节点',
  cdnWaiting: '等待下载连接',
  currentDohServer: 'DoH 解析服务器',
  currentResolverServer: '解析服务器',
  webapiConnectionStatus: 'WebAPI 连接',
  webapiConnectionIdle: '等待 WebAPI 连接',
  webapiConnectionError: '最近错误',
  dohWaiting: '等待 DoH 解析',
  resolverWaiting: '等待解析',
  safeMode: '安全',
  runnerDir: '运行目录',
  downloadsDir: '下载目录',
  serverControl: '服务控制',
  restartServer: '重启服务端',
  shutdownServer: '关闭服务端',
  appUpdate: '应用更新',
  currentVersion: '当前版本',
  latestVersion: '最新版本',
  updateStatus: '更新状态',
  updateStatusIdle: '尚未检查',
  updateStatusChecking: '正在检查更新',
  updateStatusCurrent: '已是最新版本',
  updateStatusAvailable: '发现新版本',
  updateStatusUnsupported: '当前版本没有适用的更新包',
  updateStatusDownloading: '正在下载并校验更新',
  updateStatusDownloaded: '更新包已就绪',
  updateStatusInstalling: '正在安装并重启',
  updateStatusError: '更新失败',
  checkUpdate: '检查更新',
  downloadUpdate: '下载更新',
  installUpdate: '安装并重启',
  viewRelease: '查看版本说明',
  autoUpdate: '自动更新',
  autoUpdateDesc: '发现新版本后自动下载、校验并在没有活动下载任务时安装。更新会重启 WallHub。',
  updateAvailableToast: '发现 WallHub v{version}',
  updateDownloadStarted: '已开始下载更新',
  updateInstallConfirm: '确定安装更新并重启 WallHub 吗？请先确认没有正在进行的重要操作。',
  updateCheckFailed: '检查更新失败',
  updateDownloadFailed: '下载或校验更新失败',
  updateInstallFailed: '无法安装更新',
  dockerUpdateManaged: 'Docker 自动更新已由独立容器接管；WallHub 本身不会访问 Docker Socket。',
  dockerUpdateManual: 'Docker 需要拉取新版镜像并重建容器；可启用 Compose 的 auto-update profile 自动处理。',
  downloadIntro: '调整下载目录和后台下载并发。',
  downloadDir: '下载目录',
  saveDir: '保存目录',
  mpkgTextureProfile: 'MPKG 文件转换方式',
  mpkgTextureProfileDesc: '选择转换时更看重速度还是压缩率：快速模式会更快完成；最大压缩会尽量缩小 MPKG 文件，但耗时更长。若当前环境暂不支持最大压缩，会自动使用快速模式。',
  mpkgTextureProfileFast: '快速模式',
  mpkgTextureProfileCompact: '最大压缩',
  mpkgTextureProfileCompactUnavailable: '当前环境暂不支持“最大压缩”，将自动使用“快速模式”。',
  maxConcurrentDownloads: '最大同时下载项目',
  steamCdnRoute: 'HTTP(S)/SOCKS5 代理',
  steamCdnRouteDesc: '填写 HTTP(S)/SOCKS5 代理地址后，SteamKit 下载与分块在线播放会走该代理；留空则使用系统默认网络。',
  steamCdnRouteStrategy: 'HTTP(S)/SOCKS5 代理地址',
  steamCdnNearest: '系统默认网络',
  steamCdnNearestDesc: '下载器使用系统默认网络环境。',
  steamCdnDirect: '系统默认网络',
  steamCdnDirectDesc: '下载器使用系统默认网络环境。',
  steamCdnProxy: 'HTTP(S)/SOCKS5 代理',
  steamCdnProxyDesc: '下载链路走指定 HTTP(S)/SOCKS5 代理；CDN 可能按代理出口选择。',
  steamCdnNearestShort: '系统默认',
  steamCdnDefaultShort: '系统默认',
  steamCdnDirectShort: '系统默认',
  steamCdnProxyShort: '自定义代理',
  steamHttpProxyUrl: 'HTTP(S)/SOCKS5 代理地址',
  steamHttpProxyPlaceholder: 'http://127.0.0.1:7890 或 socks5://127.0.0.1:7890',
  saveCdnRoute: '保存代理设置',
  steamKitMaxDownloads: 'SteamKit 单项目下载并发',
  steamKitMaxDownloadsDesc: '控制 DepotDownloader 的 -max-downloads。自动模式下 Windows 默认 24，Linux 默认 16，Termux 默认 12。',
  depotStreamCacheMax: '在线播放缓存上限',
  depotStreamCacheMaxDesc: '限制 SteamKit 分块在线播放缓存占用，不影响完整下载文件。',
  depotStreamCacheCustom: '自定义缓存上限',
  depotStreamCacheCustomPlaceholder: '输入 MB，例如 512 或 4096',
  clearDepotStreamCache: '立即清理缓存',
  depotStreamCacheCleared: '在线播放缓存已清理',
  effectiveValue: '实际',
  itemUnit: '项',
  current: '当前',
  defaultMark: '默认',
  steamIntro: '登录状态与 SteamKit 创意工坊访问。',
  accountStatus: '账号状态',
  loggedInAs: '已登录',
  steamUser: 'Steam 用户',
  currentNotLoggedIn: '当前未登录',
  steamNotLoggedInDownloadHint: '你未登录持有Wallpaper的Steam账号、无法下载 | 播放 Wallpaper 项目',
  logout: '退出',
  loginSteam: '登录 Steam 账号',
  steamApiTitle: 'Steam Web API',
  steamApiPlaceholder: '输入 Steam Web API Key',
  steamApiHelp: 'Steam Web API 列表查询需要有效的 API Key。缺少或无效 Key、请求失败时会明确报错，不会自动回退 Community；直接项目 ID 使用公开详情接口。',
  steamApiQuery: '获取 Steam Web API Key',
  steamDataSourceTitle: '创意工坊数据源',
  steamDataSourceLabel: '优先数据源',
  steamDataSourceHelp: '选择创意工坊列表的固定查询来源。Community 登录后使用当前 Web 会话，未登录时匿名查询；Web API 需要有效 Key；CM 需要可用的 SteamKit 登录会话。来源失败时不会自动切换。',
  experimentalIntro: '实验功能默认关闭，用于验证新的播放和下载策略；失败时会回退到稳定路径。',
  steamKitDepotStreaming: 'SteamKit 分块在线播放',
  steamKitDepotStreamingDesc: '实验性：对 depot/chunk 视频项目尝试按需读取 Steam 分块并在线播放；连接设置跟随 HTTP(S)/SOCKS5 代理，并发跟随 SteamKit 单项目下载并发。',
  prefetchNextPage: '预载下一页',
  prefetchNextPageDesc: '开启后，会在当前页加载完成时于后台请求并缓存下一页；关闭会立即取消尚未完成的预载请求。提醒：这会额外占用网络和设备资源，网络较慢或设备性能有限时可能增加加载负担。',
  wallhubSteamAccessEnhance: 'Steam 增强连接',
  wallhubSteamAccessEnhanceDesc: '开启后仅提供“智能解析”和“Hosts”两种模式。智能解析会结合 DoH/DoT 与动态可用节点，Hosts 模式则只使用你提供或自动更新的 hosts 映射。',
  wallhubSteamAccessVerboseLogs: 'Steam 增强连接详细日志',
  wallhubSteamAccessVerboseLogsDesc: '排障开关：在服务端输出解析、探测、请求尝试的 host、IP、SNI、协议、状态码和耗时。正常使用建议关闭。',
  wallhubLogLevel: '服务端日志等级',
  wallhubLogLevelDesc: 'INFO 只输出关键状态；DEBUG 会在服务端输出更详细的 Steam 网络、前端点击事件和连接层日志。',
  wallhubSteamAccessStaticCdnControl: 'Steam 图片与静态资源域名控制',
  wallhubSteamAccessStaticCdnControlDesc: '分别控制 images.steamusercontent.com 与 shared.akamai.steamstatic.com 这两个图片和静态资源域名的连接方式，以及是否复用连接。',
  wallhubSteamAccessStaticCdnHostDesc: '“内置增强”会为这个域名使用 WallHub 的连接优化；关闭连接复用后，每次请求都会重新建立连接，遇到图片或资源加载异常时可以尝试关闭。',
  builtinEnhance: '内置增强',
  reuseConnection: '复用连接',
  wallhubSteamWebApiControl: 'Steam WebAPI 控制',
  wallhubSteamWebApiControlDesc: '自定义 api.steampowered.com 的连接策略：可走直连或跟随解析器/Hosts，控制使用 HTTP 或 HTTPS。',
  wallhubSteamWebApiRouteLabel: '连接路由',
  wallhubSteamWebApiRouteDirect: '直连',
  wallhubSteamWebApiRouteFollow: '跟随解析器与 Hosts',
  wallhubSteamWebApiProtocolLabel: '协议',
  wallhubSteamWebApiHostLabel: 'API 域名',
  steamCdnLockedByAccessEnhance: 'Steam 增强连接不会锁定 HTTP(S)/SOCKS5 代理设置。',
  dohPickerTitle: '解析选择',
  dohSelectDesc: '选择 DoH 或 DoT 解析 Steam 域名 IP。',
  dohCurrent: '当前解析器',
  dohModeFastest: '最快响应',
  dohModeFixed: '固定解析器',
  dohSwitch: '切换',
  dohSave: '保存解析器',
  resolverPickerTitle: '连接模式',
  resolverSelectDesc: '在“智能解析”和“Hosts”之间切换。智能解析适合自动绕过污染，Hosts 适合使用固定映射。',
  resolverModeResolver: '智能解析',
  resolverModeHosts: 'Hosts模式',
  resolverSelectedCount: '已选择解析器',
  resolverCustomEndpoint: '自定义',
  resolverHostsTitle: 'Hosts 模式',
  resolverHostsDesc: 'Hosts 模式只使用本地持久化 hosts 映射；未命中的域名会回退普通访问路径，不会偷偷调用 DoH/DoT。',
  resolverHostsPlaceholder: '此处可以参考https://github.com/gagadog/steam_hosts',
  resolverHostsImport: '保存 hosts',
  resolverHostsFetch: '导入/刷新',
  resolverHostsUrlPlaceholder: 'https://gh-proxy.org/https://raw.githubusercontent.com/ChEnLeo-7/Github_hosts/refs/heads/main/steam-hosts',
  resolverHostsUrlExample: 'URL 示例',
  resolverHostsForkHint: '你也可以 fork Github_hosts 仓库，自行维护一份针对所在地区解析的 Hosts 文件。',
  resolverHostsAutoUpdate: '自动更新 hosts（小时）',
  resolverHostsLastUpdated: '最近更新',
  resolverHostsLastError: '最近错误',
  resolverProtocolDoh: 'DoH',
  resolverProtocolDot: 'DoT',
  resolverCurrent: '当前路线',
  resolverModeFastest: '最快响应',
  resolverModeFixed: '固定解析器',
  resolverSwitch: '管理',
  resolverSave: '添加解析器',
  steamProxyQuickOpen: 'Steam 网址代理打开',
  steamProxyQuickOpenDesc: '输入 Steam 相关网址后通过 Wallhub 代理入口打开，适合没有全局代理时访问 Steam 页面。',
  steamProxyQuickOpenPlaceholder: 'https://steamcommunity.com/ 或 https://store.steampowered.com/',
  steamProxyQuickCommunity: 'Steam 社区',
  steamProxyQuickStore: 'Steam 商店',
  steamProxyQuickWorkshop: 'Wallpaper 创意工坊',
  steamProxyQuickCharts: 'Steam 排行榜',
  openProxyUrl: '代理打开',
  appearanceIntro: '调整首页显示密度和界面语言。',
  language: '语言',
  languageDesc: '切换前端界面的显示语言。',
  accentTheme: '主题色',
  accentThemeDesc: '切换莫奈风格主题色；默认保留黑白模式。',
  accentMono: '默认黑白',
  accentBlue: '莫奈蓝',
  accentGreen: '莫奈绿',
  accentRose: '莫奈玫瑰',
  accentViolet: '莫奈紫',
  accentCustom: '自定义',
  customAccentColor: '自定义主题色',
  fixedPanelHeight: '界面固定高度',
  fixedPanelHeightDesc: '开启后设置、下载队列、详情和登录等二级界面使用固定高度，内容通过内部滚动查看。',
  detailsPresentation: '详情页样式',
  detailsPresentationDesc: '在经典详情布局和新版聚焦信息布局之间切换。',
  detailsPresentationClassic: '经典样式（旧版）',
  detailsPresentationRedesigned: '新版沉浸式布局',
  homePageSize: '首页每页卡片数量',
  homePageSizeDesc: '控制 Wallhub 首页每次加载和分页显示的卡片数量。',
  homeCardDefaultAction: '首页卡片默认按钮',
  homeCardDefaultActionDesc: '设置首页壁纸卡片底部按钮的默认操作。',
  actionPlayVideo: '播放视频',
  actionBackgroundDownload: '后台下载',
  actionClientDownload: '下载到本地',
  actionOpenSteamPage: '打开 Steam 页面',
  remoteSubscribePreparing: '正在向 Steam 提交订阅请求...',
  remoteSubscribeSuccess: '请求已发送！请查看个人订阅或电脑Wallpaper Engine',
  remoteSubscribePending: '即将订阅{dots}',
  remoteSubscriptionActive: '已订阅',
  actionUnsubscribe: '取消订阅',
  remoteUnsubscribePreparing: '正在向 Steam 提交取消订阅请求...',
  remoteUnsubscribeSuccess: '取消订阅请求已发送！请刷新个人订阅查看',
  actionSubscribe: '订阅',
  remoteFavoritePreparing: '正在向 Steam 提交收藏请求...',
  remoteFavoriteSuccess: '收藏请求已发送！请查看我的收藏',
  remoteFavoritePending: '即将收藏{dots}',
  remoteFavoriteActive: '已收藏',
  actionFavorite: '收藏',
  remoteUnfavoritePreparing: '正在向 Steam 提交取消收藏请求...',
  remoteUnfavoriteSuccess: '取消收藏请求已发送！请刷新我的收藏查看',
  actionUnfavorite: '取消收藏',
  mobileColumns: '移动端首页单行数量',
  desktopColumns: 'PC 首页单行数量',
  autoFit: '自动适配',
  auto: '自动',
  enabled: '已开启',
  disabled: '已关闭',
  runtimeReady: '运行文件已就绪',
  runtimeReadyJson: 'JSON 真实进度下载器已就绪',
  runtimeCheckSteamKit: '正在检查 SteamKit 运行文件',
  runtimeBuildSteamKit: '正在构建 SteamKit JSON 真实进度下载器',
  runtimeRelogin: '请重新登录 Steam',
  runtimeLoginRestored: '已恢复登录',
  runtimeLoginKept: '已保留登录',
  runtimeSessionUnverified: '本地登录会话未验证，请重新登录',
  runtimePrepareFailed: '运行文件准备失败',
  runtimeBuildFailed: 'SteamKit JSON 真实进度下载器构建失败',
  queueEmpty: '当前队列空空如也',
  queueStatusFilter: '下载队列状态筛选',
  queueTypeFilter: '下载队列类型筛选',
  queueFilterModeSwitch: '切换状态或类型筛选',
  queueFilterAll: '全部',
  queueFilterVideo: '视频',
  queueFilterScene: '场景',
  queueFilterWeb: '网站',
  queueFilterCompleted: '已完成',
  queueFilterDownloading: '下载中',
  queueFilterPending: '待下载',
  queueFilterFailed: '失败',
  queueFilteredEmpty: '当前筛选下没有任务',
  resumeAll: '全部开始',
  pauseAll: '全部暂停',
  clearCompletedFailed: '清理完成与失败',
  waitingRealProgress: '正在下载，等待下载器返回真实进度',
  waitingProgress: '等待真实进度',
  sizeUnknown: '大小未知',
  play: '播放',
  download: '下载',
  pause: '暂停',
  resume: '继续',
  moveUp: '上移',
  moveDown: '下移',
  delete: '删除',
  statusPending: '排队中',
  statusDownloading: '下载中',
  statusMoving: '转移中',
  statusPaused: '已暂停',
  statusError: '失败',
  statusCompleted: '已完成',
  author: '作者',
  loadingAuthor: '加载中',
  playVideo: '播放视频',
  backgroundDownload: '后台下载',
  downloadLocal: '下载到本地',
  openSteamPage: '打开 Steam 页面',
  subscriptions: '订阅数',
  favorites: '收藏数',
  views: '浏览量',
  fileSize: '文件大小',
  lastUpdated: '最后更新',
  type: '类型',
  loadingDescription: '正在加载详细描述...',
  noDescription: '暂无详细描述',
  comments: '用户留言',
  loadingComments: '正在抓取留言...',
  noComments: '暂无留言',
  genreFilterTitle: '筛选总页面',
  genreTabGenres: '标签类型',
  genreTabOfficial: '官方筛选',
  genreTabResolution: '分辨率',
  genreActiveFilters: '已选筛选',
  clear: '清除',
  selectAll: '全选',
  applyFilter: '应用筛选',
  steamLoginTitle: 'Steam 账号登录',
  cancel: '取消',
  cancelQr: '取消扫码',
  generateQr: '生成二维码',
  submitGuard: '提交验证码',
  submitSteamToken: '使用令牌登录',
  login: '登录',
  passwordLogin: '账号密码',
  qrLogin: '扫码登录',
  qrHelp: '使用 Steam 手机 App 扫描二维码，登录成功后 DepotDownloader 会在本地保存会话。',
  passwordHelp: '登录会通过 DepotDownloader 验证 Steam 账号，并在本地保存会话；不会保存密码。',
  steamUsername: 'Steam 用户名',
  steamPassword: 'Steam 密码',
  steamGuard: 'Steam Guard 验证码',
  useSteamToken: '使用 Steam 令牌登录',
  steamTokenCode: 'Steam 令牌验证码',
  steamTokenHelp: '输入 Steam 手机令牌生成的验证码，将直接使用令牌验证，不等待邮件验证码或手机确认。',
  enterSteamToken: '请输入 Steam 令牌验证码',
  qrGenerating: '正在生成二维码',
  qrStart: '点击生成二维码开始扫码登录',
  qrWaitImage: '正在生成可扫描二维码，请稍等...',
  qrWaitingOutput: '正在等待 DepotDownloader 输出二维码...',
  qrWillShow: '二维码会显示在这里',
  qrConfirmed: '已确认账号',
  qrFailed: '扫码登录失败',
  enterCredentials: '请输入用户名和密码',
  guardRequired: '需要 Steam Guard 验证码',
  loginFailed: '登录失败',
  loginStatus: '当前登录状态',
  loginStarting: '正在启动登录验证',
  phoneConfirmationRequired: '需要在 Steam 手机 App 中确认本次登录，请查看手机。',
  prevPage: '上一页',
  nextPage: '下一页',
  backToTop: '返回顶部',
  loadingWorkshop: '正在抓取 Steam 创意工坊...',
  warmingSteamIp: '正在预热SteamIP……',
  emptyWorkshop: '未找到匹配的壁纸，请尝试修改筛选条件',
  networkHint: '当前网络可能无法访问 Steam 社区服务。需要代理时请确保服务端运行环境能读取 HTTP_PROXY / HTTPS_PROXY。',
  retry: '重试',
  copyProxyDomains: '复制代理域名',
  genres: {
    Abstract: '抽象',
    Animal: '动物',
    Anime: '动漫',
    Cartoon: '卡通',
    CGI: 'CGI',
    Cyberpunk: '网络朋克',
    Fantasy: '幻想',
    Game: '游戏',
    Girls: '女性',
    Guys: '男性',
    Landscape: '风景',
    Medieval: '中世纪',
    Memes: '网络事物',
    MMD: 'MMD',
    Music: '音乐',
    Nature: '自然',
    'Pixel art': '像素艺术',
    Relaxing: '放松',
    Retro: '复古',
    'Sci-Fi': '科幻',
    Sports: '运动',
    Technology: '科技',
    Television: '电视节目',
    Vehicle: '汽车',
    Unspecified: '未指定样式',
  },
} as const;
