export const STARTUP_COPY = {
  zh: {
    title: '欢迎使用 WallHub',
    loading: '正在读取启动配置...',
    loadingHint: '服务恢复后将自动继续',
    account: 'Steam 账号',
    network: '社区连接',
    ready: '完成',
    optional: '可选',
    required: '必需',
    accountTitle: '是否登录 Steam 账号？',
    accountDesc: '登录后可使用个人订阅、收藏和完整下载能力，WallHub 也会检测当前账号是否拥有 Wallpaper Engine。',
    login: '登录 Steam',
    loginDesc: '使用本机 SteamKit 持久会话',
    skip: '暂不登录',
    skipDesc: '先以匿名方式浏览公开壁纸',
    connectedAccount: '当前已登录',
    pendingAccount: '本地会话等待验证',
    checkAccess: '检测 Wallpaper Engine 权限',
    checkingAccess: '正在检测账号权限',
    owned: '已拥有 Wallpaper Engine',
    ownedDesc: '账号权限正常，可以下载完整项目文件。',
    notOwned: '未检测到 Wallpaper Engine 权限',
    notOwnedDesc: '仍可浏览公开内容，但 Steam 可能拒绝下载项目文件。',
    unknown: '暂时无法确认账号权限',
    unknownDesc: '可以重试，或稍后在需要下载时再验证。',
    networkTitle: '检测 Steam 社区连接',
    networkDesc: 'WallHub 需要访问 Steam 社区来搜索壁纸、读取详情和加载个人列表。',
    checkingNetwork: '正在检测 Steam 社区...',
    checkingNetworkDesc: '验证 DNS、TLS 和 Workshop 页面响应',
    enhancePreparing: '正在准备内置增强连接',
    savingSettings: '正在验证增强配置',
    resolvingRoutes: '正在解析和预热 Steam IP',
    validatingRoutes: '正在验证可用线路',
    requestingWorkshop: '正在请求 Workshop 页面',
    retryingWorkshop: 'Workshop 请求超时或失败，正在重试',
    workshopAttempt: '第 {attempt}/{max} 次尝试',
    workshopRetries: '已重试 {count} 次',
    validatingResponse: '正在验证 Workshop 响应',
    elapsed: '已用时间',
    routesReady: '可用线路',
    hostsChecked: '已检查 {completed}/{total} 个核心地址',
    waitingForHosts: '正在读取核心地址',
    connected: 'Steam 社区连接正常',
    directDesc: '当前网络可以直接访问 Steam 社区。',
    enhancedDesc: '当前通过 WallHub 内置增强连接访问 Steam 社区。',
    unreachable: 'Steam 社区连接质量较差',
    unreachableDesc: '连接检测失败或超过 15 秒，推荐开启内置增强连接，为社区页面和 Web API 请求选择可用线路。',
    networkTimeout: 'Steam 社区连接检测超过 15 秒，当前连接质量较差。',
    enableEnhance: '配置内置增强',
    enhanceSetupTitle: '选择增强方式',
    enhanceSetupDesc: '配置只会在检测成功并完成引导后保存。',
    smartResolver: '智能解析',
    smartResolverDesc: '通过 DoH 或 DoT 自动解析并选择可用 Steam 线路。',
    hostsMode: 'Hosts 模式',
    hostsModeDesc: '使用你提供的 IP 与域名映射，适合维护固定线路。',
    resolverProtocol: '解析协议',
    resolverEndpoints: '解析端点',
    endpointHint: '可多选，WallHub 会优先使用响应更快的端点。',
    customEndpoint: '自定义端点',
    addEndpoint: '添加',
    invalidEndpoint: '端点格式无效',
    hostsText: 'Hosts 映射',
    hostsPlaceholder: '例如：\n1.2.3.4 steamcommunity.com',
    hostsUrl: 'Hosts 来源 URL（可选）',
    importHosts: '导入',
    importingHosts: '导入中...',
    autoUpdateHosts: '完成引导后自动更新此 URL',
    updateInterval: '更新间隔',
    hours: '小时',
    hostsUrlExample: 'URL 示例',
    hostsForkHint: '你也可以 fork Github_hosts 仓库，自行维护一份针对所在地区解析的 Hosts 文件。',
    testConfiguration: '使用此配置检测',
    cancelEnhance: '返回',
    continueWithout: '暂不开启，继续使用',
    warning: '进入主页后搜索可能无法加载，之后仍可在设置中开启增强连接。',
    retry: '重新检测',
    route: '连接方式',
    direct: '当前网络',
    enhanced: '内置增强',
    latency: '响应耗时',
    readyTitle: '关键配置已完成',
    readyDesc: 'WallHub 已记录你的账号与网络选择，现在可以开始浏览创意工坊。',
    accountSummary: '账号方式',
    networkSummary: '网络方式',
    browsingOnly: '匿名浏览',
    enter: '进入主页',
    continue: '继续',
    back: '返回',
    choose: '请先选择是否登录 Steam',
    completing: '正在进入...',
    loadingSettings: '正在读取增强配置...',
    settingsLoadFailed: '无法读取增强配置，请返回后重试。',
    invalidHosts: '请填写至少一条有效 Hosts 映射，或提供有效来源 URL。',
    removeEndpoint: '移除端点',
  },
  en: {
    title: 'Welcome to WallHub',
    loading: 'Loading startup setup...',
    loadingHint: 'Setup will continue when the service is available',
    account: 'Steam account',
    network: 'Community access',
    ready: 'Finish',
    optional: 'Optional',
    required: 'Required',
    accountTitle: 'Sign in to Steam?',
    accountDesc: 'Signing in enables subscriptions, favorites, and full downloads. WallHub will also check this account for Wallpaper Engine access.',
    login: 'Sign in to Steam',
    loginDesc: 'Use a local persistent SteamKit session',
    skip: 'Not now',
    skipDesc: 'Browse public wallpapers anonymously',
    connectedAccount: 'Currently signed in',
    pendingAccount: 'Local session pending validation',
    checkAccess: 'Check Wallpaper Engine access',
    checkingAccess: 'Checking account access',
    owned: 'Wallpaper Engine access confirmed',
    ownedDesc: 'The account can download complete project files.',
    notOwned: 'Wallpaper Engine access not found',
    notOwnedDesc: 'Public browsing still works, but Steam may reject project downloads.',
    unknown: 'Account access could not be confirmed',
    unknownDesc: 'Retry now or verify later when a download needs it.',
    networkTitle: 'Check Steam Community access',
    networkDesc: 'WallHub needs Steam Community for wallpaper search, details, and personal lists.',
    checkingNetwork: 'Checking Steam Community...',
    checkingNetworkDesc: 'Testing DNS, TLS, and the Workshop response',
    enhancePreparing: 'Preparing built-in enhancement',
    savingSettings: 'Validating enhancement settings',
    resolvingRoutes: 'Resolving and warming Steam IPs',
    validatingRoutes: 'Validating available routes',
    requestingWorkshop: 'Requesting the Workshop page',
    retryingWorkshop: 'The Workshop request timed out or failed. Retrying',
    workshopAttempt: 'Attempt {attempt} of {max}',
    workshopRetries: 'Retried {count} times',
    validatingResponse: 'Validating the Workshop response',
    elapsed: 'Elapsed',
    routesReady: 'Routes ready',
    hostsChecked: 'Checked {completed}/{total} core hosts',
    waitingForHosts: 'Reading core hosts',
    connected: 'Steam Community is reachable',
    directDesc: 'The current network can reach Steam Community directly.',
    enhancedDesc: 'Steam Community is reachable through WallHub connection enhancement.',
    unreachable: 'Steam Community connection quality is poor',
    unreachableDesc: 'The check failed or exceeded 15 seconds. We recommend built-in enhancement for Community and Web API requests.',
    networkTimeout: 'The Steam Community check exceeded 15 seconds, indicating poor connection quality.',
    enableEnhance: 'Configure built-in enhancement',
    enhanceSetupTitle: 'Choose an enhancement mode',
    enhanceSetupDesc: 'Settings are saved only after the check succeeds and setup is completed.',
    smartResolver: 'Smart resolver',
    smartResolverDesc: 'Use DoH or DoT to resolve and select reachable Steam routes automatically.',
    hostsMode: 'Hosts mode',
    hostsModeDesc: 'Use IP-to-host mappings you provide for fixed, maintained routes.',
    resolverProtocol: 'Resolver protocol',
    resolverEndpoints: 'Resolver endpoints',
    endpointHint: 'Select multiple endpoints; WallHub prioritizes responsive routes.',
    customEndpoint: 'Custom endpoint',
    addEndpoint: 'Add',
    invalidEndpoint: 'Invalid endpoint format',
    hostsText: 'Hosts mappings',
    hostsPlaceholder: 'Example:\n1.2.3.4 steamcommunity.com',
    hostsUrl: 'Hosts source URL (optional)',
    importHosts: 'Import',
    importingHosts: 'Importing...',
    autoUpdateHosts: 'Update this URL automatically after setup',
    updateInterval: 'Update interval',
    hours: 'hours',
    hostsUrlExample: 'Example URL',
    hostsForkHint: 'You can also fork the Github_hosts repository and maintain a Hosts file resolved for your own region.',
    testConfiguration: 'Test this configuration',
    cancelEnhance: 'Back',
    continueWithout: 'Continue without it',
    warning: 'Search may not load. Enhancement can still be enabled from Settings later.',
    retry: 'Check again',
    route: 'Route',
    direct: 'Current network',
    enhanced: 'Built-in enhancement',
    latency: 'Response',
    readyTitle: 'Important setup is complete',
    readyDesc: 'WallHub has recorded your account and network choices. The Workshop is ready.',
    accountSummary: 'Account',
    networkSummary: 'Network',
    browsingOnly: 'Anonymous browsing',
    enter: 'Open home',
    continue: 'Continue',
    back: 'Back',
    choose: 'Choose whether to sign in to Steam',
    completing: 'Opening...',
    loadingSettings: 'Loading enhancement settings...',
    settingsLoadFailed: 'Enhancement settings could not be loaded. Go back and retry.',
    invalidHosts: 'Add a valid Hosts mapping or provide a valid source URL.',
    removeEndpoint: 'Remove endpoint',
  },
} as const;

export type StartupCopy = typeof STARTUP_COPY.zh | typeof STARTUP_COPY.en;
