'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

function writeDirectNetworkSource(projectDir) {
  const directNetworkPath = path.join(projectDir, 'WallHubDirectNetwork.cs');
  fs.writeFileSync(directNetworkPath, [
    '// This file is subject to the terms and conditions defined',
    "// in file 'LICENSE', which is part of this source code package.",
    '',
    '// Auto-generated by WallHub. Disables system proxy inside DepotDownloader when Steam content is direct.',
    'using System;',
    'using System.Net;',
    'using System.Net.Http;',
    '',
    'namespace DepotDownloader',
    '{',
    '    static class WallHubDirectNetwork',
    '    {',
    '        public static void ApplyFromEnvironment()',
    '        {',
    '            if (Environment.GetEnvironmentVariable("WALLHUB_STEAM_CONTENT_DIRECT") != "1")',
    '            {',
    '                return;',
    '            }',
    '            try',
    '            {',
    '                HttpClient.DefaultProxy = new WallHubNoProxy();',
    '                WebRequest.DefaultWebProxy = null;',
    '                Environment.SetEnvironmentVariable("HTTP_PROXY", null);',
    '                Environment.SetEnvironmentVariable("HTTPS_PROXY", null);',
    '                Environment.SetEnvironmentVariable("ALL_PROXY", null);',
    '                Environment.SetEnvironmentVariable("http_proxy", null);',
    '                Environment.SetEnvironmentVariable("https_proxy", null);',
    '                Environment.SetEnvironmentVariable("all_proxy", null);',
    '            }',
    '            catch { }',
    '        }',
    '',
    '        private sealed class WallHubNoProxy : IWebProxy',
    '        {',
    '            public ICredentials Credentials { get; set; }',
    '            public Uri GetProxy(Uri destination) => destination;',
    '            public bool IsBypassed(Uri host) => true;',
    '        }',
    '    }',
    '}',
    ''
  ].join(os.EOL), 'utf8');
}

module.exports = { writeDirectNetworkSource };
