'use strict';

function wallHubSteam3NetworkPatchSource() {
  return [
    '        private static SteamClient WallHubCreateSteamClient(SteamConfiguration clientConfiguration)',
    '        {',
    '            var protocol = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_STEAM3_PROTOCOL") ?? string.Empty).Trim().ToLowerInvariant();',
    '            if (protocol == "websocket" || protocol == "ws" || protocol == "wss")',
    '            {',
    '                Console.Error.WriteLine("WALLHUB_STEAM3_PROTOCOL:websocket");',
    '            }',
    '            else if (!string.IsNullOrWhiteSpace(protocol) && protocol != "default" && protocol != "auto")',
    '            {',
    '                Console.Error.WriteLine($"WALLHUB_STEAM3_PROTOCOL:{protocol}");',
    '            }',
    '',
    '            return new SteamClient(WallHubBuildSteamConfiguration(clientConfiguration, protocol));',
    '        }',
    '',
    '        private static SteamConfiguration WallHubBuildSteamConfiguration(SteamConfiguration baseConfiguration, string protocol)',
    '        {',
    '            var useWebSocket = protocol == "websocket" || protocol == "ws" || protocol == "wss";',
    '',
    '            return SteamConfiguration.Create(builder =>',
    '            {',
    '                if (baseConfiguration != null)',
    '                {',
    '                    builder.WithCellID(baseConfiguration.CellID)',
    '                        .WithConnectionTimeout(baseConfiguration.ConnectionTimeout)',
    '                        .WithDefaultPersonaStateFlags(baseConfiguration.DefaultPersonaStateFlags)',
    '                        .WithDirectoryFetch(baseConfiguration.AllowDirectoryFetch)',
    '                        .WithMachineInfoProvider(baseConfiguration.MachineInfoProvider)',
    '                        .WithProtocolTypes(baseConfiguration.ProtocolTypes)',
    '                        .WithServerListProvider(baseConfiguration.ServerListProvider)',
    '                        .WithUniverse(baseConfiguration.Universe)',
    '                        .WithWebAPIBaseAddress(baseConfiguration.WebAPIBaseAddress);',
    '',
    '                    if (!string.IsNullOrWhiteSpace(baseConfiguration.WebAPIKey))',
    '                    {',
    '                        builder.WithWebAPIKey(baseConfiguration.WebAPIKey);',
    '                    }',
    '                }',
    '',
    '                if (useWebSocket)',
    '                {',
    '                    builder.WithProtocolTypes(ProtocolTypes.WebSocket);',
    '                }',
    '',
    '                builder.WithHttpClientFactory(WallHubCreateApiHttpClient);',
    '            });',
    '        }',
    '',
    '        private static HttpClient WallHubCreateApiHttpClient(HttpClientPurpose purpose)',
    '        {',
    '            var brokerUrl = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_WEBAPI_BROKER_URL") ?? string.Empty).Trim();',
    '            var brokerToken = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_WEBAPI_BROKER_TOKEN") ?? string.Empty).Trim();',
    '            if (!string.IsNullOrWhiteSpace(brokerUrl) && !string.IsNullOrWhiteSpace(brokerToken))',
    '            {',
    '                Console.Error.WriteLine($"WALLHUB_STEAM3_API_BROKER_REQUIRED:{purpose}");',
    '                return new HttpClient(new WallHubSteamWebApiBrokerHandler(WallHubCreateApiSocketsHandler(), brokerUrl, brokerToken), disposeHandler: true) { Timeout = TimeSpan.FromSeconds(WallHubApiTimeoutSeconds()) };',
    '            }',
    '',
    '            Console.Error.WriteLine($"WALLHUB_STEAM3_API_BROKER_DISABLED:{purpose}");',
    '            return new HttpClient(WallHubCreateApiSocketsHandler(), disposeHandler: true) { Timeout = TimeSpan.FromSeconds(WallHubApiTimeoutSeconds()) };',
    '        }',
    '',
    '        private static SocketsHttpHandler WallHubCreateApiSocketsHandler()',
    '        {',
        '            var handler = new SocketsHttpHandler',
        '            {',
        '                UseProxy = !string.Equals(Environment.GetEnvironmentVariable("WALLHUB_STEAM_CDN_ROUTE_STRATEGY"), "nearest", StringComparison.OrdinalIgnoreCase),',
        '                ConnectTimeout = TimeSpan.FromSeconds(3),',
    '                PooledConnectionIdleTimeout = TimeSpan.FromSeconds(30),',
    '                PooledConnectionLifetime = TimeSpan.FromMinutes(2),',
    '            };',
    '',
        '            if (WallHubSteamCdnDirectMode()) handler.ConnectCallback = async (context, cancellationToken) =>',
        '            {',
        '                var host = context.DnsEndPoint.Host;',
        '                var port = context.DnsEndPoint.Port;',
        '                if (Environment.GetEnvironmentVariable("DEPOTDOWNLOADER_DEBUG") == "1") Console.Error.WriteLine($"WALLHUB_STEAM3_CONNECT_START:{host}:{port}");',
        '                if (WallHubShouldResolveDepotHost(host) && WallHubSteamCdnDirectMode())',
    '                {',
    '                    foreach (var ip in await WallHubResolveDepotHostAsync(host, port, true, cancellationToken).ConfigureAwait(false))',
    '                    {',
    '                        cancellationToken.ThrowIfCancellationRequested();',
    '                        Socket socket = null;',
    '                        try',
    '                        {',
    '                            using var connectCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);',
    '                            connectCts.CancelAfter(TimeSpan.FromSeconds(2));',
    '                            socket = new Socket(ip.AddressFamily, SocketType.Stream, ProtocolType.Tcp) { NoDelay = true };',
    '                            await socket.ConnectAsync(new IPEndPoint(ip, port), connectCts.Token).ConfigureAwait(false);',
    '                            Console.Error.WriteLine($"WALLHUB_STEAM3_API_CONNECT:{host}->{ip}:{port}");',
    '                            var stream = new NetworkStream(socket, ownsSocket: true);',
    '                            socket = null;',
    '                            return stream;',
    '                        }',
    '                        catch (Exception ex)',
    '                        {',
    '                            socket?.Dispose();',
    '                            if (cancellationToken.IsCancellationRequested) throw;',
    '                            Console.Error.WriteLine($"WALLHUB_STEAM3_API_CONNECT_FAILED:{host}->{ip}:{port}:{ex.Message}");',
    '                        }',
    '                    }',
    '                }',
    '',
        '                if (WallHubShouldResolveDepotHost(host) && !WallHubShouldResolveApiHost(host) && WallHubDepotResolverConfigured()) throw new HttpRequestException($"Steam CDN route is unavailable for {host}.");',
        '                return await WallHubOpenSocketAsync(host, port, cancellationToken).ConfigureAwait(false);',
    '            };',
    '',
    '            return handler;',
    '        }',
    '',
    '        private sealed class WallHubSteamWebApiBrokerHandler : HttpMessageHandler',
    '        {',
    '            private readonly HttpMessageInvoker fallbackInvoker;',
    '            private readonly string brokerUrl;',
    '            private readonly string brokerToken;',
    '',
    '            public WallHubSteamWebApiBrokerHandler(HttpMessageHandler fallbackHandler, string brokerUrl, string brokerToken)',
    '            {',
    '                fallbackInvoker = new HttpMessageInvoker(fallbackHandler, disposeHandler: true);',
    '                this.brokerUrl = brokerUrl;',
    '                this.brokerToken = brokerToken;',
    '            }',
    '',
    '            protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)',
    '            {',
    '                var uri = request.RequestUri;',
    '                if (uri == null || !WallHubShouldResolveApiHost(uri.Host))',
    '                {',
    '                    Console.Error.WriteLine($"WALLHUB_STEAM3_HTTP_FALLBACK_START:{uri?.Host ?? "unknown"}");',
    '                    var fallbackResponse = await fallbackInvoker.SendAsync(request, cancellationToken).ConfigureAwait(false);',
    '                    Console.Error.WriteLine($"WALLHUB_STEAM3_HTTP_FALLBACK_HEADERS:{uri?.Host ?? "unknown"}:{(int)fallbackResponse.StatusCode}");',
    '                    return fallbackResponse;',
    '                }',
    '',
    '                byte[] contentBytes = null;',
    '                if (request.Content != null)',
    '                {',
    '                    contentBytes = await request.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);',
    '                }',
    '',
    '                try',
    '                {',
    '                    using var brokerRequest = WallHubCreateBrokerRequest(request, contentBytes, brokerUrl, brokerToken);',
    '                    Console.Error.WriteLine($"WALLHUB_STEAM3_API_BROKER:{uri.Host}:{uri.PathAndQuery}");',
    '                    return await WallHubApiBootstrapClient.SendAsync(brokerRequest, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);',
    '                }',
    '                catch (Exception ex)',
    '                {',
    '                    if (cancellationToken.IsCancellationRequested) throw;',
    '                    Console.Error.WriteLine($"WALLHUB_STEAM3_API_BROKER_FAILED:{uri.Host}:{ex.Message}");',
    '                    using var fallbackRequest = WallHubCloneOriginalRequest(request, contentBytes);',
    '                    return await fallbackInvoker.SendAsync(fallbackRequest, cancellationToken).ConfigureAwait(false);',
    '                }',
    '            }',
    '',
    '            protected override void Dispose(bool disposing)',
    '            {',
    '                if (disposing)',
    '                {',
    '                    fallbackInvoker.Dispose();',
    '                }',
    '                base.Dispose(disposing);',
    '            }',
    '        }',
    '',
    '        private static HttpRequestMessage WallHubCreateBrokerRequest(HttpRequestMessage original, byte[] contentBytes, string brokerUrl, string brokerToken)',
    '        {',
    '            var uri = original.RequestUri;',
    '            var path = string.IsNullOrWhiteSpace(uri.PathAndQuery) ? "/" : uri.PathAndQuery;',
    '            var port = uri.IsDefaultPort ? 443 : uri.Port;',
    '            var separator = brokerUrl.Contains("?") ? "&" : "?";',
    '            var brokerUri = $"{brokerUrl}{separator}host={Uri.EscapeDataString(uri.Host)}&port={port}&path={Uri.EscapeDataString(path)}";',
    '            var request = new HttpRequestMessage(original.Method, brokerUri);',
    '            request.Headers.TryAddWithoutValidation("x-wallhub-resolver-token", brokerToken);',
    '            request.Headers.TryAddWithoutValidation("x-wallhub-target-host", uri.Host);',
    '            request.Headers.TryAddWithoutValidation("x-wallhub-target-port", port.ToString());',
    '            request.Headers.TryAddWithoutValidation("x-wallhub-target-path", path);',
    '            WallHubCopyHeaders(original.Headers, request.Headers);',
    '            if (contentBytes != null)',
    '            {',
    '                request.Content = new ByteArrayContent(contentBytes);',
    '                WallHubCopyHeaders(original.Content.Headers, request.Content.Headers);',
    '            }',
    '            return request;',
    '        }',
    '',
    '        private static HttpRequestMessage WallHubCloneOriginalRequest(HttpRequestMessage original, byte[] contentBytes)',
    '        {',
    '            var request = new HttpRequestMessage(original.Method, original.RequestUri);',
    '            WallHubCopyHeaders(original.Headers, request.Headers);',
    '            if (contentBytes != null)',
    '            {',
    '                request.Content = new ByteArrayContent(contentBytes);',
    '                WallHubCopyHeaders(original.Content.Headers, request.Content.Headers);',
    '            }',
    '            return request;',
    '        }',
    '',
    '        private static void WallHubCopyHeaders(System.Net.Http.Headers.HttpHeaders source, System.Net.Http.Headers.HttpHeaders destination)',
    '        {',
    '            foreach (var header in source)',
    '            {',
    '                if (WallHubBrokerHopByHopHeaders.Contains(header.Key)) continue;',
    '                destination.TryAddWithoutValidation(header.Key, header.Value);',
    '            }',
    '        }',
    '',
    '        private static readonly HashSet<string> WallHubBrokerHopByHopHeaders = new HashSet<string>(StringComparer.OrdinalIgnoreCase)',
    '        {',
    '            "Host", "Connection", "Keep-Alive", "Proxy-Authenticate", "Proxy-Authorization", "TE", "Trailer", "Transfer-Encoding", "Upgrade", "Content-Length"',
    '        };',
    '',
    '        private static int WallHubApiTimeoutSeconds()',
    '        {',
    '            var raw = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_WEBAPI_TIMEOUT_SECONDS") ?? string.Empty).Trim();',
    '            if (int.TryParse(raw, out var seconds) && seconds >= 3 && seconds <= 30) return seconds;',
    '            return 8;',
    '        }',
    '',
    '        private static async Task<NetworkStream> WallHubOpenSocketAsync(string host, int port, CancellationToken cancellationToken)',
    '        {',
    '            var socket = new Socket(SocketType.Stream, ProtocolType.Tcp) { NoDelay = true };',
    '            await socket.ConnectAsync(host, port, cancellationToken).ConfigureAwait(false);',
    '            return new NetworkStream(socket, ownsSocket: true);',
    '        }',
    '',
        '        private static bool WallHubShouldResolveApiHost(string host)',
        '        {',
        '            var value = (host ?? string.Empty).Trim().ToLowerInvariant();',
        '            return value == "api.steampowered.com" || value == "community.steam-api.com";',
        '        }',
        '',
        '        private static bool WallHubShouldResolveDepotHost(string host)',
        '        {',
        '            var value = (host ?? string.Empty).Trim().ToLowerInvariant();',
        '            if (WallHubShouldResolveApiHost(value)) return true;',
        '            if (value.EndsWith(".steamcontent.com", StringComparison.Ordinal) || value.EndsWith(".eccdnx.com", StringComparison.Ordinal) || value.EndsWith(".pphimalayanrt.com", StringComparison.Ordinal)) return true;',
        '            return System.Text.RegularExpressions.Regex.IsMatch(value, "^[a-z0-9-]+\\\\.steam\\\\.[a-z0-9-]+\\\\.com$");',
        '        }',
        '',
        '        private static bool WallHubSteamCdnDirectMode()',
        '        {',
        '            return !string.Equals(Environment.GetEnvironmentVariable("WALLHUB_STEAM_CDN_ROUTE_STRATEGY"), "proxy", StringComparison.OrdinalIgnoreCase);',
        '        }',
        '',
    '        private static async Task<List<IPAddress>> WallHubResolveDepotHostAsync(string host, int port, bool useRoute, CancellationToken cancellationToken)',
    '        {',
    '            var bridge = await WallHubResolveViaBridgeAsync(host, port, cancellationToken).ConfigureAwait(false);',
    '            if (bridge.Count > 0)',
    '            {',
    '                Console.Error.WriteLine($"WALLHUB_STEAM3_RESOLVE:{host}->{string.Join(",", bridge)} source=wallhub-api");',
    '                return bridge;',
    '            }',
    '            return new List<IPAddress>();',
    '        }',
    '',
    '        private static bool WallHubDepotResolverConfigured()',
    '        {',
    '            return !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("WALLHUB_DEPOT_RESOLVER_URL"))',
    '                && !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("WALLHUB_DEPOT_RESOLVER_TOKEN"));',
    '        }',
    '',
    '        private static async Task<List<IPAddress>> WallHubResolveViaBridgeAsync(string host, int port, CancellationToken cancellationToken)',
    '        {',
    '            var output = new List<IPAddress>();',
    '            var resolverUrl = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_RESOLVER_URL") ?? string.Empty).Trim();',
    '            var resolverToken = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_RESOLVER_TOKEN") ?? string.Empty).Trim();',
    '            if (string.IsNullOrWhiteSpace(resolverUrl) || string.IsNullOrWhiteSpace(resolverToken)) return output;',
    '            try',
    '            {',
        '                var separator = resolverUrl.Contains("?") ? "&" : "?";',
        '                using var request = new HttpRequestMessage(HttpMethod.Get, $"{resolverUrl}{separator}host={Uri.EscapeDataString(host)}&port={port}&route=1");',
        '                request.Headers.TryAddWithoutValidation("x-wallhub-resolver-token", resolverToken);',
        '                Console.Error.WriteLine($"WALLHUB_STEAM3_RESOLVER_START:{host}");',
        '                using var response = await WallHubApiBootstrapClient.SendAsync(request, cancellationToken).ConfigureAwait(false);',
        '                Console.Error.WriteLine($"WALLHUB_STEAM3_RESOLVER_HEADERS:{host}:{(int)response.StatusCode}");',
    '                response.EnsureSuccessStatusCode();',
    '                using var stream = await response.Content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(false);',
    '                using var json = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken).ConfigureAwait(false);',
    '                if (!json.RootElement.TryGetProperty("ips", out var ips)) return output;',
    '                foreach (var item in ips.EnumerateArray())',
    '                {',
    '                    if (IPAddress.TryParse(item.GetString(), out var ip) && !output.Contains(ip)) output.Add(ip);',
    '                }',
    '            }',
    '            catch (Exception ex)',
    '            {',
    '                Console.Error.WriteLine($"WALLHUB_STEAM3_RESOLVER_BRIDGE_FAILED:{host}:{ex.Message}");',
    '            }',
    '            return output;',
    '        }',
    '',
    '        private static readonly HttpClient WallHubApiBootstrapClient = new HttpClient(new SocketsHttpHandler',
    '        {',
    '            UseProxy = false,',
    '            ConnectTimeout = TimeSpan.FromSeconds(5),',
    '            PooledConnectionIdleTimeout = TimeSpan.FromSeconds(30),',
    '            PooledConnectionLifetime = TimeSpan.FromMinutes(2),',
    '        }) { Timeout = TimeSpan.FromSeconds(10) };'
  ].join('\n');
}

module.exports = { wallHubSteam3NetworkPatchSource };
