'use strict';

function streamWorkerTemplateTail() {
  return [
    '        private static async Task<StreamPlan> BuildPlanAsync(Steam3Session steam3, DownloadConfig config, uint appId, ulong publishedFileId)',
    '        {',
    '            var contentIds = new List<ulong>();',
    '            await CollectContentIdsAsync(steam3, appId, publishedFileId, contentIds).ConfigureAwait(false);',
    '            if (contentIds.Count == 0)',
    '            {',
    '                throw new ContentDownloaderException($"Published file {publishedFileId} does not expose depot/chunk content.");',
    '            }',
    '',
    '            await steam3.RequestAppInfo(appId).ConfigureAwait(false);',
    '            var depots = ContentDownloader.GetSteam3AppSection(appId, EAppInfoSection.Depots);',
    '            var workshopDepot = depots["workshopdepot"].AsUnsignedInteger();',
    '            if (workshopDepot == 0)',
    '            {',
    '                workshopDepot = appId;',
    '            }',
    '            await steam3.RequestDepotKey(workshopDepot, appId).ConfigureAwait(false);',
    '            if (!steam3.DepotKeys.TryGetValue(workshopDepot, out var depotKey))',
    '            {',
    '                throw new ContentDownloaderException($"No valid depot key for {workshopDepot}.");',
    '            }',
    '',
    '            var tempRoot = Path.Combine(Path.GetTempPath(), "wallhub-depot-stream-" + Guid.NewGuid().ToString("N"));',
    '            Directory.CreateDirectory(tempRoot);',
    '            try',
    '            {',
    '                foreach (var manifestId in contentIds)',
    '                {',
    '                    var manifest = await DownloadManifestAsync(steam3, config, appId, workshopDepot, manifestId, depotKey, tempRoot).ConfigureAwait(false);',
    '                    var file = PickVideoFile(manifest);',
    '                    if (file == null)',
    '                    {',
    '                        continue;',
    '                    }',
    '                    return new StreamPlan',
    '                    {',
    '                        AppId = appId,',
    '                        PublishedFileId = publishedFileId,',
    '                        DepotId = workshopDepot,',
    '                        ManifestId = manifestId,',
    '                        FileName = file.FileName,',
    '                        Size = file.TotalSize,',
    '                        DepotKey = depotKey,',
    '                        Manifest = manifest,',
    '                        File = file',
    '                    };',
    '                }',
    '            }',
    '            finally',
    '            {',
    '                try { Directory.Delete(tempRoot, true); } catch { }',
    '            }',
    '',
    '            throw new ContentDownloaderException($"No video file was found in published file {publishedFileId}.");',
    '        }',
    '',
    '        private static async Task CollectContentIdsAsync(Steam3Session steam3, uint appId, ulong publishedFileId, List<ulong> contentIds)',
    '        {',
    '            var details = await steam3.GetPublishedFileDetails(appId, publishedFileId).ConfigureAwait(false);',
    '            var fileType = (EWorkshopFileType)details.file_type;',
    '            if (fileType == EWorkshopFileType.Collection)',
    '            {',
    '                foreach (var child in details.children)',
    '                {',
    '                    await CollectContentIdsAsync(steam3, appId, child.publishedfileid, contentIds).ConfigureAwait(false);',
    '                }',
    '                return;',
    '            }',
    '            if (details.hcontent_file > 0)',
    '            {',
    '                contentIds.Add(details.hcontent_file);',
    '            }',
    '        }',
    '',
    '        private static async Task<DepotManifest> DownloadManifestAsync(Steam3Session steam3, DownloadConfig config, uint appId, uint depotId, ulong manifestId, byte[] depotKey, string tempRoot)',
    '        {',
    '            var cdnPool = new CDNClientPool(steam3, appId);',
    '            await cdnPool.UpdateServerList().ConfigureAwait(false);',
    '            var requestCode = await steam3.GetDepotManifestRequestCodeAsync(depotId, appId, manifestId, ContentDownloader.DEFAULT_BRANCH).ConfigureAwait(false);',
    '            var failures = new List<Exception>();',
    '            var attempts = 0;',
    '            var maxAttempts = Math.Max(3, Math.Min(12, config.MaxDownloads <= 0 ? 6 : config.MaxDownloads));',
    '            while (attempts < maxAttempts)',
    '            {',
    '                Server connection = null;',
    '                try',
    '                {',
    '                    attempts++;',
    '                    connection = cdnPool.GetConnection();',
    '                    WallHubLogCdnHost(connection);',
    '                    string cdnToken = null;',
    '                    if (steam3.CDNAuthTokens.TryGetValue((depotId, connection.Host), out var authTokenCallbackPromise))',
    '                    {',
    '                        var result = await authTokenCallbackPromise.Task.ConfigureAwait(false);',
    '                        cdnToken = result.Token;',
    '                    }',
    '                    var manifest = await cdnPool.CDNClient.DownloadManifestAsync(depotId, manifestId, requestCode, connection, depotKey, cdnPool.ProxyServer, cdnToken).ConfigureAwait(false);',
    '                    cdnPool.ReturnConnection(connection);',
    '                    return manifest;',
    '                }',
    '                catch (SteamKitWebRequestException e)',
    '                {',
    '                    failures.Add(e);',
    '                    if (connection != null && e.StatusCode == HttpStatusCode.Forbidden && !steam3.CDNAuthTokens.ContainsKey((depotId, connection.Host)))',
    '                    {',
    '                        await steam3.RequestCDNAuthToken(appId, depotId, connection).ConfigureAwait(false);',
    '                        cdnPool.ReturnConnection(connection);',
    '                        attempts--;',
    '                        continue;',
    '                    }',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    Console.Error.WriteLine($"CDN manifest retry {attempts}/{maxAttempts} failed on {(connection?.Host ?? "unknown")}: {e.Message}");',
    '                }',
    '                catch (Exception e)',
    '                {',
    '                    failures.Add(e);',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    Console.Error.WriteLine($"CDN manifest retry {attempts}/{maxAttempts} failed on {(connection?.Host ?? "unknown")}: {e.Message}");',
    '                }',
    '            }',
    '            var last = failures.Count > 0 ? failures[failures.Count - 1] : null;',
    '            throw new ContentDownloaderException($"Failed to download depot manifest {manifestId} after {attempts} CDN attempt(s). Last error: {last?.Message ?? "unknown"}");',
    '        }',
    '',
    '        private static DepotManifest.FileData PickVideoFile(DepotManifest manifest)',
    '        {',
    '            static bool IsVideo(string name)',
    '            {',
    '                var ext = Path.GetExtension(name ?? string.Empty).ToLowerInvariant();',
    '                return ext is ".mp4" or ".webm" or ".wmv" or ".avi" or ".mkv" or ".mov" or ".m4v";',
    '            }',
    '            return manifest.Files',
    '                .Where(f => !f.Flags.HasFlag(EDepotFileFlag.Directory) && IsVideo(f.FileName))',
    '                .OrderByDescending(f => f.TotalSize)',
    '                .FirstOrDefault();',
    '        }',
    '',
    '        private static readonly object WallHubCdnHostLogLock = new object();',
    '        private static readonly HashSet<string> WallHubLoggedCdnHosts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);',
    '        private static void WallHubLogCdnHost(Server server)',
    '        {',
    '            try',
    '            {',
    '                var host = server.Host ?? server.VHost ?? string.Empty;',
    '                if (string.IsNullOrWhiteSpace(host)) return;',
    '                lock (WallHubCdnHostLogLock)',
    '                {',
    '                    if (!WallHubLoggedCdnHosts.Add(host)) return;',
    '                }',
    '                Console.WriteLine($"WALLHUB_DEPOT_CDN_HOST:{{\\"host\\":\\"{host.Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"")}\\",\\"vhost\\":\\"{(server.VHost ?? string.Empty).Replace("\\\\", "\\\\\\\\").Replace("\\"", "\\\\\\"")}\\",\\"port\\":{server.Port}}}");',
    '            }',
    '            catch { }',
    '        }',
    '',
    '        private static void WallHubDisableSystemProxy()',
    '        {',
    '            if (Environment.GetEnvironmentVariable("WALLHUB_STEAM_CONTENT_DIRECT") != "1")',
    '            {',
    '                return;',
    '            }',
    '            try',
    '            {',
    '                HttpClient.DefaultProxy = new WallHubNoProxy();',
    '                WebRequest.DefaultWebProxy = null;',
    '            }',
    '            catch { }',
    '        }',
    '',
    '        private sealed class WallHubNoProxy : IWebProxy',
    '        {',
    '            public ICredentials Credentials { get; set; }',
    '            public Uri GetProxy(Uri destination) => destination;',
    '            public bool IsBypassed(Uri host) => true;',
    '        }',
    '',
    '        private static async Task<StreamChunkRead> DownloadStreamChunkAsync(Steam3Session steam3, CDNClientPool cdnPool, StreamPlan plan, DepotManifest.ChunkData chunk, CancellationToken cancellationToken)',
    '        {',
    '            var buffer = new byte[(int)chunk.UncompressedLength];',
    '            var written = await DownloadChunkAsync(steam3, cdnPool, plan, chunk, buffer, cancellationToken).ConfigureAwait(false);',
    '            return new StreamChunkRead',
    '            {',
    '                Chunk = chunk,',
    '                Buffer = buffer,',
    '                Written = written',
    '            };',
    '        }',
    '',
    '        private static async Task<int> DownloadChunkAsync(Steam3Session steam3, CDNClientPool cdnPool, StreamPlan plan, DepotManifest.ChunkData chunk, byte[] destination, CancellationToken cancellationToken)',
    '        {',
    '            var failures = new List<Exception>();',
    '            var maxAttempts = WallHubChunkMaxAttempts();',
    '            for (var attempt = 1; attempt <= maxAttempts; attempt++)',
    '            {',
    '                cancellationToken.ThrowIfCancellationRequested();',
    '                Server connection = null;',
    '                using var attemptCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);',
    '                attemptCts.CancelAfter(TimeSpan.FromSeconds(WallHubChunkAttemptTimeoutSeconds()));',
    '                var attemptToken = attemptCts.Token;',
    '                try',
    '                {',
    '                    connection = cdnPool.GetConnection();',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_STAGE:{attempt}/{maxAttempts}:connection:{connection?.Host ?? "unknown"}");',
    '                    WallHubLogCdnHost(connection);',
    '                    string cdnToken = null;',
    '                    if (steam3.CDNAuthTokens.TryGetValue((plan.DepotId, connection.Host), out var authTokenCallbackPromise))',
    '                    {',
    '                        Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_STAGE:{attempt}/{maxAttempts}:auth-wait:{connection.Host}");',
    '                        var result = await authTokenCallbackPromise.Task.WaitAsync(attemptToken).ConfigureAwait(false);',
    '                        cdnToken = result.Token;',
    '                        Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_STAGE:{attempt}/{maxAttempts}:auth-ready:{connection.Host}");',
    '                    }',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_STAGE:{attempt}/{maxAttempts}:http-start:{connection.Host}");',
    '                    var written = await cdnPool.CDNClient.DownloadDepotChunkAsync(steam3.steamClient, plan.DepotId, chunk, connection, destination, plan.DepotKey, cdnPool.ProxyServer, cdnToken, null, attemptToken).ConfigureAwait(false);',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_STAGE:{attempt}/{maxAttempts}:http-done:{connection.Host}:{written}");',
    '                    if (written <= 0)',
    '                    {',
    '                        throw new ContentDownloaderException("Failed to download depot chunk.");',
    '                    }',
    '                    cdnPool.ReturnConnection(connection);',
    '                    return written;',
    '                }',
    '                catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)',
    '                {',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    throw;',
    '                }',
    '                catch (OperationCanceledException e) when (attemptCts.IsCancellationRequested)',
    '                {',
    '                    failures.Add(e);',
    '                    var timeoutHost = connection?.Host ?? "unknown";',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_RETRY:{attempt}/{maxAttempts}:timeout:{timeoutHost}");',
    '                }',
    '                catch (SteamKitWebRequestException e)',
    '                {',
    '                    failures.Add(e);',
    '                    if (connection != null && e.StatusCode == HttpStatusCode.Forbidden && (!steam3.CDNAuthTokens.TryGetValue((plan.DepotId, connection.Host), out var tokenTask) || !tokenTask.Task.IsCompleted))',
    '                    {',
    '                        try',
    '                        {',
    '                            await steam3.RequestCDNAuthToken(plan.AppId, plan.DepotId, connection).WaitAsync(attemptToken).ConfigureAwait(false);',
    '                            cdnPool.ReturnConnection(connection);',
    '                            Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_RETRY:{attempt}/{maxAttempts}:auth:{connection.Host}");',
    '                            continue;',
    '                        }',
    '                        catch (OperationCanceledException) when (cancellationToken.IsCancellationRequested)',
    '                        {',
    '                            cdnPool.ReturnBrokenConnection(connection);',
    '                            throw;',
    '                        }',
    '                        catch (Exception authError)',
    '                        {',
    '                            failures.Add(authError);',
    '                            var authHost = connection.Host ?? "unknown";',
    '                            cdnPool.ReturnBrokenConnection(connection);',
    '                            Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_RETRY:{attempt}/{maxAttempts}:auth-failed:{authHost}:{authError.Message}");',
    '                            continue;',
    '                        }',
    '                    }',
    '                    var httpHost = connection?.Host ?? "unknown";',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_RETRY:{attempt}/{maxAttempts}:http:{httpHost}:{e.Message}");',
    '                }',
    '                catch (Exception e)',
    '                {',
    '                    failures.Add(e);',
    '                    var failedHost = connection?.Host ?? "unknown";',
    '                    if (connection != null) cdnPool.ReturnBrokenConnection(connection);',
    '                    Console.Error.WriteLine($"WALLHUB_DEPOT_CDN_CHUNK_RETRY:{attempt}/{maxAttempts}:failed:{failedHost}:{e.Message}");',
    '                }',
    '            }',
    '            var last = failures.Count > 0 ? failures[failures.Count - 1] : null;',
    '            throw new ContentDownloaderException($"Failed to download depot chunk after {maxAttempts} CDN attempt(s). Last error: {last?.Message ?? "unknown"}");',
    '        }',
    '',
    '        private static int WallHubChunkAttemptTimeoutSeconds()',
    '        {',
    '            var raw = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_STREAM_CHUNK_ATTEMPT_TIMEOUT_SECONDS") ?? string.Empty).Trim();',
    '            if (int.TryParse(raw, out var seconds) && seconds >= 5 && seconds <= 60) return seconds;',
    '            return 12;',
    '        }',
    '',
    '        private static int WallHubChunkMaxAttempts()',
    '        {',
    '            var raw = (Environment.GetEnvironmentVariable("WALLHUB_DEPOT_STREAM_CHUNK_MAX_ATTEMPTS") ?? string.Empty).Trim();',
    '            if (int.TryParse(raw, out var attempts) && attempts >= 2 && attempts <= 8) return attempts;',
    '            return 4;',
    '        }',
    '    }',
    '}',
    ''
  ];
}

module.exports = { streamWorkerTemplateTail };
