import * as React from 'react';

export const TEXT = {
  zh: {
    languageName: '中文',
    languageChinese: '中文',
    languageEnglish: 'English',
    settings: '设置',
    close: '关闭',
    back: '返回',
    search: '搜索',
    selectedTags: '已选标签',
    searchSelectedTags: '搜索所选标签',
    unknown: '未知',
    noCover: '无封面',
    loading: '正在加载...',
    noResults: '暂无结果',
    homeTitle: 'Steam 创意工坊壁纸',
    homeApprox: '约',
    homeItems: '项',
    homePagesPrefix: '共',
    homePagesSuffix: '页',
    searchHint: '搜索壁纸名称、项目ID 或作者ID：author:114514',
    exactPhrase: '精确匹配短语',
    themeToggle: '切换主题',
    themeMode: '显示模式',
    themeModeDesc: '跟随系统为默认；也可以固定日间或夜间模式。',
    themeSystem: '跟随系统',
    themeLight: '日间模式',
    themeDark: '夜间模式',
    queue: '下载队列',
    sortBy: '排序依据',
    sortTrend: '最热门',
    sortRecent: '最近',
    sortTopRated: '评分最高',
    sortVotes: '最多投票',
    sortSubscribers: '最多订阅',
    sortPersonalSubscriptions: '个人订阅',
    sortMyFavorites: '我的收藏',
    sortVoted: '已投票',
    sortFriendsFavorites: '好友收藏',
    sortFriendsCreated: '好友创建',
    sortFollowedCreated: '关注者创建',
    timeSort: '时间排序',
    today: '今天',
    week: '一周',
    month: '一个月',
    threeMonths: '三个月',
    halfYear: '半年',
    year: '一年',
    allTime: '有史以来',
    typeSelect: '类型选择',
    homeFilterMultiSelect: '首页筛选多选',
    homeFilterMultiSelectDesc: '开启后类型和年龄评级可多选；关闭后恢复单选。',
    all: '全部',
    scene: '场景',
    video: '视频',
    web: '网页',
    application: '应用',
    ageRating: '年龄评级',
    ratingEveryone: '大众级',
    ratingQuestionable: '家长指导级',
    ratingMature: '限制成人级',
    filter: '筛选',
    filterAllShort: '全',
    grid: '网格',
    list: '列表',
    untitledWallpaper: '未命名壁纸',
    subscribe: '订阅',
    subscribeOpen: '打开订阅',
    clientPreparing: '正在准备客户端下载...',
    clientSent: '下载已发送到浏览器',
    normalDownload: '正常下载',
    downloadStartTitle: '选择下载方式',
    downloadPkgSource: '下载ZIP压缩包',
    downloadDesktopFormat: '（桌面端格式）',
    downloadMpkgMobile: '下载MPKG文件',
    downloadMobileFormat: '（移动端格式）',
    mpkgConvertOnly: '仅转换MPKG文件',
    downloadChoiceTitle: '选择下载格式',
    copied: '已复制',
    copyTitle: '复制标题',
    mpkgConvertDownload: 'Mpkg转换并下载',
    mpkgPreparingStart: '正在准备 MPKG...',
    mpkgSent: 'MPKG 已发送到浏览器',
    mpkgConvertOnlyPreparing: '正在转换 MPKG，仅保留到项目文件夹...',
    mpkgConvertOnlySourceDownloadingProgress: '正在下载壁纸源文件，已等待 {seconds} 秒；下载完成后将转换并保留 MPKG',
    mpkgConvertOnlyPreparingProgress: '正在转换 MPKG，已等待 {seconds} 秒；完成后将保留在项目 Mpkg 文件夹',
    mpkgConvertOnlyReady: 'MPKG 已转换并保存到项目 Mpkg 文件夹',
    queuedDownload: '已加入后台下载队列',
    downloadCompleted: '{title} 下载完成',
    videoPlayer: '视频播放',
    videoQueued: '视频已加入准备队列，请在下载队列查看进度',
    videoLoading: '视频正在加载...',
    videoPreparing: '视频正在下载并准备播放',
    videoPlayerControls: '视频播放器控件',
    videoPlayerControlsDesc: '默认模式使用浏览器原生控制栏；兼容模式使用 WallHub 控制栏，适用于 Edge 和部分 Android WebView。',
    videoPlayerModeDefault: '默认模式',
    videoPlayerModeCompatibility: '兼容模式',
    videoPlay: '播放',
    videoPause: '暂停',
    videoMute: '静音',
    videoUnmute: '取消静音',
    videoSeek: '播放进度',
    videoVolume: '音量',
    videoPlaybackRate: '播放速度',
    videoEnterFullscreen: '进入全屏',
    videoExitFullscreen: '退出全屏',
    videoShortcutsLabel: '播放器快捷键',
    videoShortcutPlayPause: '播放 / 暂停',
    videoShortcutBack5: '后退 5 秒',
    videoShortcutForward5: '快进 5 秒',
    videoShortcutHold: '长按',
    videoShortcutSpeed: '2x 倍速播放',
    videoShortcutFullscreen: '全屏',
    videoShortcutExitFullscreen: '退出全屏',
    videoSpeedPlaying: '正在以 2x倍速播放……',
    settingsSaved: '设置已保存',
    saveApply: '保存并应用',
    deleted: '已删除',
    loginRequired: '需要登录拥有 Wallpaper Engine 的 Steam 账号后再继续',
    loggedOut: '已退出登录',
    restartingServer: '服务端正在重启',
    shutdownConfirm: '确定要关闭服务端吗？关闭后需要在终端重新启动。',
    shuttingDownServer: '服务端正在关闭',
    loginSuccess: '登录成功',
    navServer: '服务端',
    navDownload: '下载设置',
    navSteam: 'Steam账号',
    navAppearance: '外观',
    navExperimental: '实验性',
    serverIntro: '运行方式、目录和服务进程控制。',
    runMode: '运行模式',
    runStatus: '运行状态',
    contentMode: '内容模式',
    currentCdnNode: '当前 CDN 节点',
    cdnWaiting: '等待下载连接',
    currentDohServer: 'DoH 解析服务器',
    currentResolverServer: '解析服务器',
    webapiConnectionStatus: 'WebAPI 连接',
    webapiConnectionIdle: '等待 WebAPI 连接',
    webapiConnectionError: '最近错误',
    dohWaiting: '等待 DoH 解析',
    resolverWaiting: '等待解析',
    safeMode: '安全',
    runnerDir: '运行目录',
    downloadsDir: '下载目录',
    serverControl: '服务控制',
    restartServer: '重启服务端',
    shutdownServer: '关闭服务端',
    downloadIntro: '调整下载目录和后台下载并发。',
    downloadDir: '下载目录',
    saveDir: '保存目录',
    mpkgTextureProfile: 'MPKG 文件转换方式',
    mpkgTextureProfileDesc: '选择转换时更看重速度还是压缩率：快速模式会更快完成；最大压缩会尽量缩小 MPKG 文件，但耗时更长。若当前环境暂不支持最大压缩，会自动使用快速模式。',
    mpkgTextureProfileFast: '快速模式',
    mpkgTextureProfileCompact: '最大压缩',
    mpkgTextureProfileCompactUnavailable: '当前环境暂不支持“最大压缩”，将自动使用“快速模式”。',
    maxConcurrentDownloads: '最大同时下载项目',
    steamCdnRoute: 'HTTP(S)/SOCKS5 代理',
    steamCdnRouteDesc: '填写 HTTP(S)/SOCKS5 代理地址后，SteamKit 下载与分块在线播放会走该代理；留空则使用系统默认网络。',
    steamCdnRouteStrategy: 'HTTP(S)/SOCKS5 代理地址',
    steamCdnNearest: '系统默认网络',
    steamCdnNearestDesc: '下载器使用系统默认网络环境。',
    steamCdnDirect: '系统默认网络',
    steamCdnDirectDesc: '下载器使用系统默认网络环境。',
    steamCdnProxy: 'HTTP(S)/SOCKS5 代理',
    steamCdnProxyDesc: '下载链路走指定 HTTP(S)/SOCKS5 代理；CDN 可能按代理出口选择。',
    steamCdnNearestShort: '系统默认',
    steamCdnDefaultShort: '系统默认',
    steamCdnDirectShort: '系统默认',
    steamCdnProxyShort: '自定义代理',
    steamHttpProxyUrl: 'HTTP(S)/SOCKS5 代理地址',
    steamHttpProxyPlaceholder: 'http://127.0.0.1:7890 或 socks5://127.0.0.1:7890',
    saveCdnRoute: '保存代理设置',
    steamKitMaxDownloads: 'SteamKit 单项目下载并发',
    steamKitMaxDownloadsDesc: '控制 DepotDownloader 的 -max-downloads。自动模式下 Windows 默认 24，Linux 默认 16，Termux 默认 12。',
    depotStreamCacheMax: '在线播放缓存上限',
    depotStreamCacheMaxDesc: '限制 SteamKit 分块在线播放缓存占用，不影响完整下载文件。',
    depotStreamCacheCustom: '自定义缓存上限',
    depotStreamCacheCustomPlaceholder: '输入 MB，例如 512 或 4096',
    clearDepotStreamCache: '立即清理缓存',
    depotStreamCacheCleared: '在线播放缓存已清理',
    effectiveValue: '实际',
    itemUnit: '项',
    current: '当前',
    defaultMark: '默认',
    steamIntro: '登录状态与 SteamKit 创意工坊访问。',
    accountStatus: '账号状态',
    loggedInAs: '已登录',
    steamUser: 'Steam 用户',
    currentNotLoggedIn: '当前未登录',
    steamNotLoggedInDownloadHint: '你未登录持有Wallpaper的Steam账号、无法下载 | 播放 Wallpaper 项目',
    logout: '退出',
    loginSteam: '登录 Steam 账号',
    steamApiTitle: 'Steam Web API',
    steamApiPlaceholder: '输入 Steam Web API Key',
    steamApiHelp: '配置后，公开创意工坊列表和搜索优先通过 Web API 获取；留空时使用 Steam Community 页面。',
    steamApiQuery: '获取 Steam Web API Key',
    experimentalIntro: '实验功能默认关闭，用于验证新的播放和下载策略；失败时会回退到稳定路径。',
    steamKitDepotStreaming: 'SteamKit 分块在线播放',
    steamKitDepotStreamingDesc: '实验性：对 depot/chunk 视频项目尝试按需读取 Steam 分块并在线播放；连接设置跟随 HTTP(S)/SOCKS5 代理，并发跟随 SteamKit 单项目下载并发。',
    prefetchNextPage: '预载下一页',
    prefetchNextPageDesc: '开启后，会在当前页加载完成时于后台请求并缓存下一页；关闭会立即取消尚未完成的预载请求。提醒：这会额外占用网络和设备资源，网络较慢或设备性能有限时可能增加加载负担。',
    wallhubSteamAccessEnhance: 'Steam 增强连接',
    wallhubSteamAccessEnhanceDesc: '开启后仅提供“智能解析”和“Hosts”两种模式。智能解析会结合 DoH/DoT 与动态可用节点，Hosts 模式则只使用你提供或自动更新的 hosts 映射。',
    wallhubSteamAccessVerboseLogs: 'Steam 增强连接详细日志',
    wallhubSteamAccessVerboseLogsDesc: '排障开关：在服务端输出解析、探测、请求尝试的 host、IP、SNI、协议、状态码和耗时。正常使用建议关闭。',
    wallhubLogLevel: '服务端日志等级',
    wallhubLogLevelDesc: 'INFO 只输出关键状态；DEBUG 会在服务端输出更详细的 Steam 网络、前端点击事件和连接层日志。',
    wallhubSteamAccessStaticCdnControl: 'Steam 图片与静态资源域名控制',
    wallhubSteamAccessStaticCdnControlDesc: '分别控制 images.steamusercontent.com 与 shared.akamai.steamstatic.com 这两个图片和静态资源域名的连接方式，以及是否复用连接。',
    wallhubSteamAccessStaticCdnHostDesc: '“内置增强”会为这个域名使用 WallHub 的连接优化；关闭连接复用后，每次请求都会重新建立连接，遇到图片或资源加载异常时可以尝试关闭。',
    builtinEnhance: '内置增强',
    reuseConnection: '复用连接',
    wallhubSteamWebApiControl: 'Steam WebAPI 控制',
    wallhubSteamWebApiControlDesc: '自定义 api.steampowered.com 的连接策略：可走直连或跟随解析器/Hosts，控制使用 HTTP 或 HTTPS。',
    wallhubSteamWebApiRouteLabel: '连接路由',
    wallhubSteamWebApiRouteDirect: '直连',
    wallhubSteamWebApiRouteFollow: '跟随解析器与 Hosts',
    wallhubSteamWebApiProtocolLabel: '协议',
    wallhubSteamWebApiHostLabel: 'API 域名',
    steamCdnLockedByAccessEnhance: 'Steam 增强连接不会锁定 HTTP(S)/SOCKS5 代理设置。',
    dohPickerTitle: '解析选择',
    dohSelectDesc: '选择 DoH 或 DoT 解析 Steam 域名 IP。',
    dohCurrent: '当前解析器',
    dohModeFastest: '最快响应',
    dohModeFixed: '固定解析器',
    dohSwitch: '切换',
    dohSave: '保存解析器',
    resolverPickerTitle: '连接模式',
    resolverSelectDesc: '在“智能解析”和“Hosts”之间切换。智能解析适合自动绕过污染，Hosts 适合使用固定映射。',
    resolverModeResolver: '智能解析',
    resolverModeHosts: 'Hosts模式',
    resolverSelectedCount: '已选择解析器',
    resolverCustomEndpoint: '自定义',
    resolverHostsTitle: 'Hosts 模式',
    resolverHostsDesc: 'Hosts 模式只使用本地持久化 hosts 映射；未命中的域名会回退普通访问路径，不会偷偷调用 DoH/DoT。',
    resolverHostsPlaceholder: '此处可以参考https://github.com/gagadog/steam_hosts',
    resolverHostsImport: '保存 hosts',
    resolverHostsFetch: '导入/刷新',
    resolverHostsUrlPlaceholder: 'https://gh-proxy.org/https://raw.githubusercontent.com/ChEnLeo-7/Github_hosts/refs/heads/main/steam-hosts',
    resolverHostsAutoUpdate: '自动更新 hosts（小时）',
    resolverHostsLastUpdated: '最近更新',
    resolverHostsLastError: '最近错误',
    resolverProtocolDoh: 'DoH',
    resolverProtocolDot: 'DoT',
    resolverCurrent: '当前路线',
    resolverModeFastest: '最快响应',
    resolverModeFixed: '固定解析器',
    resolverSwitch: '管理',
    resolverSave: '添加解析器',
    steamProxyQuickOpen: 'Steam 网址代理打开',
    steamProxyQuickOpenDesc: '输入 Steam 相关网址后通过 Wallhub 代理入口打开，适合没有全局代理时访问 Steam 页面。',
    steamProxyQuickOpenPlaceholder: 'https://steamcommunity.com/ 或 https://store.steampowered.com/',
    steamProxyQuickCommunity: 'Steam 社区',
    steamProxyQuickStore: 'Steam 商店',
    steamProxyQuickWorkshop: 'Wallpaper 创意工坊',
    steamProxyQuickCharts: 'Steam 排行榜',
    openProxyUrl: '代理打开',
    appearanceIntro: '调整首页显示密度和界面语言。',
    language: '语言',
    languageDesc: '切换前端界面的显示语言。',
    accentTheme: '主题色',
    accentThemeDesc: '切换莫奈风格主题色；默认保留黑白模式。',
    accentMono: '默认黑白',
    accentBlue: '莫奈蓝',
    accentGreen: '莫奈绿',
    accentRose: '莫奈玫瑰',
    accentViolet: '莫奈紫',
    accentCustom: '自定义',
    customAccentColor: '自定义主题色',
    fixedPanelHeight: '界面固定高度',
    fixedPanelHeightDesc: '开启后设置、下载队列、详情和登录等二级界面使用固定高度，内容通过内部滚动查看。',
    detailsPresentation: '详情页样式',
    detailsPresentationDesc: '在经典详情布局和新版聚焦信息布局之间切换。',
    detailsPresentationClassic: '经典样式（旧版）',
    detailsPresentationRedesigned: '新版沉浸式布局',
    homePageSize: '首页每页卡片数量',
    homePageSizeDesc: '控制 Wallhub 首页每次加载和分页显示的卡片数量。',
    homeCardDefaultAction: '首页卡片默认按钮',
    homeCardDefaultActionDesc: '设置首页壁纸卡片底部按钮的默认操作。',
    actionPlayVideo: '播放视频',
    actionBackgroundDownload: '后台下载',
    actionClientDownload: '下载到本地',
    actionOpenSteamPage: '打开 Steam 页面',
    remoteSubscribePreparing: '正在向 Steam 提交订阅请求...',
    remoteSubscribeSuccess: '请求已发送！请查看个人订阅或电脑Wallpaper Engine',
    remoteSubscribePending: '即将订阅{dots}',
    remoteSubscriptionActive: '已订阅',
    actionUnsubscribe: '取消订阅',
    remoteUnsubscribePreparing: '正在向 Steam 提交取消订阅请求...',
    remoteUnsubscribeSuccess: '取消订阅请求已发送！请刷新个人订阅查看',
    actionSubscribe: '订阅',
    remoteFavoritePreparing: '正在向 Steam 提交收藏请求...',
    remoteFavoriteSuccess: '收藏请求已发送！请查看我的收藏',
    remoteFavoritePending: '即将收藏{dots}',
    remoteFavoriteActive: '已收藏',
    actionFavorite: '收藏',
    remoteUnfavoritePreparing: '正在向 Steam 提交取消收藏请求...',
    remoteUnfavoriteSuccess: '取消收藏请求已发送！请刷新我的收藏查看',
    actionUnfavorite: '取消收藏',
    mobileColumns: '移动端首页单行数量',
    desktopColumns: 'PC 首页单行数量',
    autoFit: '自动适配',
    auto: '自动',
    enabled: '已开启',
    disabled: '已关闭',
    runtimeReady: '运行文件已就绪',
    runtimeReadyJson: 'JSON 真实进度下载器已就绪',
    runtimeCheckSteamKit: '正在检查 SteamKit 运行文件',
    runtimeBuildSteamKit: '正在构建 SteamKit JSON 真实进度下载器',
    runtimeRelogin: '请重新登录 Steam',
    runtimeLoginRestored: '已恢复登录',
    runtimeLoginKept: '已保留登录',
    runtimeSessionUnverified: '本地登录会话未验证，请重新登录',
    runtimePrepareFailed: '运行文件准备失败',
    runtimeBuildFailed: 'SteamKit JSON 真实进度下载器构建失败',
    queueEmpty: '当前队列空空如也',
    queueStatusFilter: '下载队列状态筛选',
    queueTypeFilter: '下载队列类型筛选',
    queueFilterModeSwitch: '切换状态或类型筛选',
    queueFilterAll: '全部',
    queueFilterVideo: '视频',
    queueFilterScene: '场景',
    queueFilterWeb: '网站',
    queueFilterCompleted: '已完成',
    queueFilterDownloading: '下载中',
    queueFilterPending: '待下载',
    queueFilterFailed: '失败',
    queueFilteredEmpty: '当前筛选下没有任务',
    resumeAll: '全部开始',
    pauseAll: '全部暂停',
    clearCompletedFailed: '清理完成与失败',
    waitingRealProgress: '正在下载，等待下载器返回真实进度',
    waitingProgress: '等待真实进度',
    sizeUnknown: '大小未知',
    play: '播放',
    download: '下载',
    pause: '暂停',
    resume: '继续',
    moveUp: '上移',
    moveDown: '下移',
    delete: '删除',
    statusPending: '排队中',
    statusDownloading: '下载中',
    statusMoving: '转移中',
    statusPaused: '已暂停',
    statusError: '失败',
    statusCompleted: '已完成',
    author: '作者',
    loadingAuthor: '加载中',
    playVideo: '播放视频',
    backgroundDownload: '后台下载',
    downloadLocal: '下载到本地',
    openSteamPage: '打开 Steam 页面',
    subscriptions: '订阅数',
    favorites: '收藏数',
    views: '浏览量',
    fileSize: '文件大小',
    lastUpdated: '最后更新',
    type: '类型',
    loadingDescription: '正在加载详细描述...',
    noDescription: '暂无详细描述',
    comments: '用户留言',
    loadingComments: '正在抓取留言...',
    noComments: '暂无留言',
    genreFilterTitle: '筛选总页面',
    genreTabGenres: '标签类型',
    genreTabOfficial: '官方筛选',
    genreTabResolution: '分辨率',
    genreActiveFilters: '已选筛选',
    clear: '清除',
    selectAll: '全选',
    applyFilter: '应用筛选',
    steamLoginTitle: 'Steam 账号登录',
    cancel: '取消',
    cancelQr: '取消扫码',
    generateQr: '生成二维码',
    submitGuard: '提交验证码',
    submitSteamToken: '使用令牌登录',
    login: '登录',
    passwordLogin: '账号密码',
    qrLogin: '扫码登录',
    qrHelp: '使用 Steam 手机 App 扫描二维码，登录成功后 DepotDownloader 会在本地保存会话。',
    passwordHelp: '登录会通过 DepotDownloader 验证 Steam 账号，并在本地保存会话；不会保存密码。',
    steamUsername: 'Steam 用户名',
    steamPassword: 'Steam 密码',
    steamGuard: 'Steam Guard 验证码',
    useSteamToken: '使用 Steam 令牌登录',
    steamTokenCode: 'Steam 令牌验证码',
    steamTokenHelp: '输入 Steam 手机令牌生成的验证码，将直接使用令牌验证，不等待邮件验证码或手机确认。',
    enterSteamToken: '请输入 Steam 令牌验证码',
    qrGenerating: '正在生成二维码',
    qrStart: '点击生成二维码开始扫码登录',
    qrWaitImage: '正在生成可扫描二维码，请稍等...',
    qrWaitingOutput: '正在等待 DepotDownloader 输出二维码...',
    qrWillShow: '二维码会显示在这里',
    qrConfirmed: '已确认账号',
    qrFailed: '扫码登录失败',
    enterCredentials: '请输入用户名和密码',
    guardRequired: '需要 Steam Guard 验证码',
    loginFailed: '登录失败',
    loginStatus: '当前登录状态',
    loginStarting: '正在启动登录验证',
    phoneConfirmationRequired: '需要在 Steam 手机 App 中确认本次登录，请查看手机。',
    prevPage: '上一页',
    nextPage: '下一页',
    backToTop: '返回顶部',
    loadingWorkshop: '正在抓取 Steam 创意工坊...',
    warmingSteamIp: '正在预热SteamIP……',
    emptyWorkshop: '未找到匹配的壁纸，请尝试修改筛选条件',
    networkHint: '当前网络可能无法访问 Steam 社区服务。需要代理时请确保服务端运行环境能读取 HTTP_PROXY / HTTPS_PROXY。',
    retry: '重试',
    copyProxyDomains: '复制代理域名',
    genres: {
      Abstract: '抽象',
      Animal: '动物',
      Anime: '动漫',
      Cartoon: '卡通',
      CGI: 'CGI',
      Cyberpunk: '网络朋克',
      Fantasy: '幻想',
      Game: '游戏',
      Girls: '女性',
      Guys: '男性',
      Landscape: '风景',
      Medieval: '中世纪',
      Memes: '网络事物',
      MMD: 'MMD',
      Music: '音乐',
      Nature: '自然',
      'Pixel art': '像素艺术',
      Relaxing: '放松',
      Retro: '复古',
      'Sci-Fi': '科幻',
      Sports: '运动',
      Technology: '科技',
      Television: '电视节目',
      Vehicle: '汽车',
      Unspecified: '未指定样式',
    },
  },
  en: {
    languageName: 'English',
    languageChinese: '中文',
    languageEnglish: 'English',
    settings: 'Settings',
    close: 'Close',
    back: 'Back',
    search: 'Search',
    selectedTags: 'Selected tags',
    searchSelectedTags: 'Search selected tags',
    unknown: 'Unknown',
    noCover: 'No cover',
    loading: 'Loading...',
    noResults: 'No results',
    homeTitle: 'Steam Workshop Wallpapers',
    homeApprox: 'About',
    homeItems: 'items',
    homePagesPrefix: '',
    homePagesSuffix: 'pages',
    searchHint: 'Search wallpaper name, project ID, or author ID: author:114514',
    exactPhrase: 'Exact phrase',
    themeToggle: 'Toggle theme',
    themeMode: 'Display mode',
    themeModeDesc: 'System is the default. You can also force light or dark mode.',
    themeSystem: 'Follow system',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    queue: 'Download queue',
    sortBy: 'Sort by',
    sortTrend: 'Trending',
    sortRecent: 'Recent',
    sortTopRated: 'Top rated',
    sortVotes: 'Most voted',
    sortSubscribers: 'Most subscribed',
    sortPersonalSubscriptions: 'My subscriptions',
    sortMyFavorites: 'My favorites',
    sortVoted: 'Voted items',
    sortFriendsFavorites: 'Friends favorites',
    sortFriendsCreated: 'Friends created',
    sortFollowedCreated: 'Followed authors',
    timeSort: 'Time range',
    today: 'Today',
    week: 'Week',
    month: 'Month',
    threeMonths: '3 months',
    halfYear: '6 months',
    year: 'Year',
    allTime: 'All time',
    typeSelect: 'Type',
    homeFilterMultiSelect: 'Multi-select home filters',
    homeFilterMultiSelectDesc: 'Enable multi-select for type and age rating filters. Disable it to use single-select mode.',
    all: 'All',
    scene: 'Scene',
    video: 'Video',
    web: 'Web',
    application: 'Application',
    ageRating: 'Age rating',
    ratingEveryone: 'Everyone',
    ratingQuestionable: 'Questionable',
    ratingMature: 'Mature',
    filter: 'Filter',
    filterAllShort: 'All',
    grid: 'Grid',
    list: 'List',
    untitledWallpaper: 'Untitled wallpaper',
    subscribe: 'Subscribe',
    subscribeOpen: 'Open subscription',
    clientPreparing: 'Preparing client download...',
    clientSent: 'Download sent to browser',
    normalDownload: 'Download now',
    downloadStartTitle: 'Choose download method',
    downloadPkgSource: 'Download ZIP archive',
    downloadDesktopFormat: '(desktop format)',
    downloadMpkgMobile: 'Download MPKG file',
    downloadMobileFormat: '(mobile format)',
    mpkgConvertOnly: 'Convert MPKG only',
    downloadChoiceTitle: 'Choose download format',
    copied: 'Copied',
    copyTitle: 'Copy title',
    mpkgConvertDownload: 'Convert MPKG and download',
    mpkgPreparingStart: 'Preparing MPKG...',
    mpkgSent: 'MPKG sent to browser',
    mpkgConvertOnlyPreparing: 'Converting MPKG and keeping it in the project folder...',
    mpkgConvertOnlySourceDownloadingProgress: 'Downloading the wallpaper source — waiting {seconds}s. The MPKG will be converted and retained when the download is complete.',
    mpkgConvertOnlyPreparingProgress: 'Converting MPKG — waiting {seconds}s. The result will remain in the project Mpkg folder.',
    mpkgConvertOnlyReady: 'MPKG converted and saved in the project Mpkg folder',
    queuedDownload: 'Added to background download queue',
    downloadCompleted: 'Download completed: {title}',
    videoPlayer: 'Video player',
    videoQueued: 'Video was added to the preparation queue. Check progress in the download queue.',
    videoLoading: 'Loading video...',
    videoPreparing: 'Downloading and preparing video playback',
    videoPlayerControls: 'Video player controls',
    videoPlayerControlsDesc: 'Default mode uses the browser controls. Compatibility mode uses WallHub controls for Edge and some Android WebView versions.',
    videoPlayerModeDefault: 'Default mode',
    videoPlayerModeCompatibility: 'Compatibility mode',
    videoPlay: 'Play',
    videoPause: 'Pause',
    videoMute: 'Mute',
    videoUnmute: 'Unmute',
    videoSeek: 'Playback position',
    videoVolume: 'Volume',
    videoPlaybackRate: 'Playback speed',
    videoEnterFullscreen: 'Enter fullscreen',
    videoExitFullscreen: 'Exit fullscreen',
    videoShortcutsLabel: 'Player shortcuts',
    videoShortcutPlayPause: 'Play / pause',
    videoShortcutBack5: 'Back 5s',
    videoShortcutForward5: 'Forward 5s',
    videoShortcutHold: 'Hold',
    videoShortcutSpeed: '2x playback',
    videoShortcutFullscreen: 'Fullscreen',
    videoShortcutExitFullscreen: 'Exit fullscreen',
    videoSpeedPlaying: 'Playing at 2x speed…',
    settingsSaved: 'Settings saved',
    saveApply: 'Save and apply',
    deleted: 'Deleted',
    loginRequired: 'Please log in with a Steam account that owns Wallpaper Engine before continuing',
    loggedOut: 'Logged out',
    restartingServer: 'Server is restarting',
    shutdownConfirm: 'Shut down the server? You will need to start it again from the terminal.',
    shuttingDownServer: 'Server is shutting down',
    loginSuccess: 'Login successful',
    navServer: 'Server',
    navDownload: 'Downloads',
    navSteam: 'Steam account',
    navAppearance: 'Appearance',
    navExperimental: 'Experimental',
    serverIntro: 'Runtime mode, folders, and server process controls.',
    runMode: 'Runtime mode',
    runStatus: 'Runtime status',
    contentMode: 'Content mode',
    currentCdnNode: 'Current CDN node',
    cdnWaiting: 'Waiting for download connection',
    currentDohServer: 'DoH resolver',
    currentResolverServer: 'Resolver',
    webapiConnectionStatus: 'WebAPI connection',
    webapiConnectionIdle: 'Waiting for WebAPI connection',
    webapiConnectionError: 'Last error',
    dohWaiting: 'Waiting for DoH resolution',
    resolverWaiting: 'Waiting for resolution',
    safeMode: 'Safe',
    runnerDir: 'Runner folder',
    downloadsDir: 'Download folder',
    serverControl: 'Server control',
    restartServer: 'Restart server',
    shutdownServer: 'Shut down server',
    downloadIntro: 'Adjust the download folder and background download concurrency.',
    downloadDir: 'Download folder',
    saveDir: 'Save folder',
    mpkgTextureProfile: 'MPKG conversion mode',
    mpkgTextureProfileDesc: 'Choose whether conversion prioritizes speed or compression: Fast mode finishes sooner; Maximum compression makes a smaller MPKG file but takes longer. If maximum compression is unavailable, WallHub uses Fast mode automatically.',
    mpkgTextureProfileFast: 'Fast mode',
    mpkgTextureProfileCompact: 'Maximum compression',
    mpkgTextureProfileCompactUnavailable: 'Maximum compression is unavailable here, so WallHub will use Fast mode.',
    maxConcurrentDownloads: 'Max concurrent downloads',
    steamCdnRoute: 'HTTP(S)/SOCKS5 proxy',
    steamCdnRouteDesc: 'Enter an HTTP(S)/SOCKS5 proxy URL for SteamKit downloads and chunk streaming. Leave empty to use the default system network.',
    steamCdnRouteStrategy: 'HTTP(S)/SOCKS5 proxy URL',
    steamCdnNearest: 'Default system network',
    steamCdnNearestDesc: 'Downloader processes use the default system network environment.',
    steamCdnDirect: 'Default system network',
    steamCdnDirectDesc: 'Downloader processes use the default system network environment.',
    steamCdnProxy: 'HTTP(S)/SOCKS5 proxy',
    steamCdnProxyDesc: 'Download traffic uses the configured HTTP(S)/SOCKS5 proxy. CDN may be chosen near that proxy endpoint.',
    steamCdnNearestShort: 'Default network',
    steamCdnDefaultShort: 'Default network',
    steamCdnDirectShort: 'Default network',
    steamCdnProxyShort: 'Custom proxy',
    steamHttpProxyUrl: 'HTTP(S)/SOCKS5 proxy URL',
    steamHttpProxyPlaceholder: 'http://127.0.0.1:7890 or socks5://127.0.0.1:7890',
    saveCdnRoute: 'Save proxy settings',
    steamKitMaxDownloads: 'SteamKit per-item concurrency',
    steamKitMaxDownloadsDesc: 'Controls DepotDownloader -max-downloads. Auto uses 24 on Windows, 16 on Linux, and 12 on Termux.',
    depotStreamCacheMax: 'Streaming cache limit',
    depotStreamCacheMaxDesc: 'Limits SteamKit chunk-stream cache usage. Completed downloads are not affected.',
    depotStreamCacheCustom: 'Custom cache limit',
    depotStreamCacheCustomPlaceholder: 'Enter MB, for example 512 or 4096',
    clearDepotStreamCache: 'Clear cache now',
    depotStreamCacheCleared: 'Streaming cache cleared',
    effectiveValue: 'Effective',
    itemUnit: 'items',
    current: 'Current',
    defaultMark: 'default',
    steamIntro: 'Login status and SteamKit Workshop access.',
    accountStatus: 'Account status',
    loggedInAs: 'Logged in',
    steamUser: 'Steam user',
    currentNotLoggedIn: 'Not logged in',
    steamNotLoggedInDownloadHint: 'You are not logged in with a Steam account that owns Wallpaper Engine, so you cannot download | play Wallpaper items',
    logout: 'Log out',
    loginSteam: 'Log in to Steam',
    steamApiTitle: 'Steam Web API',
    steamApiPlaceholder: 'Enter Steam Web API key',
    steamApiHelp: 'When set, public Workshop browsing and search prefer the Web API. Leave it empty to use Steam Community pages.',
    steamApiQuery: 'Get a Steam Web API key',
    experimentalIntro: 'Experimental options are off by default and are used to test new playback and downloader strategies. Unavailable paths fall back to stable behavior.',
    steamKitDepotStreaming: 'SteamKit chunk streaming',
    steamKitDepotStreamingDesc: 'Experimental: try on-demand Steam depot/chunk streaming for video playback. It follows the HTTP(S)/SOCKS5 proxy setting and SteamKit per-item concurrency settings.',
    prefetchNextPage: 'Preload next page',
    prefetchNextPageDesc: 'When enabled, fetch and cache the following page after the current page loads. Turning it off immediately cancels an unfinished preload. Note: this adds network and device work, so it can increase loading pressure on slower connections or devices.',
    wallhubSteamAccessEnhance: 'Steam enhanced access',
    wallhubSteamAccessEnhanceDesc: 'When enabled, WallHub only exposes two modes: Smart Resolver and Hosts. Smart Resolver combines DoH/DoT with dynamic reachable nodes, while Hosts mode only uses your provided or auto-updated hosts mappings.',
    wallhubSteamAccessVerboseLogs: 'Verbose Steam access logs',
    wallhubSteamAccessVerboseLogsDesc: 'Troubleshooting switch: log resolver, probe and request attempts with host, IP, SNI, protocol, status and elapsed time on the server. Keep it off for normal use.',
    wallhubLogLevel: 'Server log level',
    wallhubLogLevelDesc: 'INFO logs key state only; DEBUG enables detailed Steam network, frontend click, and connection-layer logs on the server.',
    wallhubSteamAccessStaticCdnControl: 'Steam image and static asset domain controls',
    wallhubSteamAccessStaticCdnControlDesc: 'Control connection handling and reuse for the two Steam image and static asset domains: images.steamusercontent.com and shared.akamai.steamstatic.com.',
    wallhubSteamAccessStaticCdnHostDesc: 'Built-in enhancement uses WallHub connection optimization for this domain. Turning reuse off creates a fresh connection for every request, which can help when images or assets fail to load.',
    builtinEnhance: 'Built-in enhance',
    reuseConnection: 'Reuse connection',
    wallhubSteamWebApiControl: 'Steam WebAPI Control',
    wallhubSteamWebApiControlDesc: 'Customize api.steampowered.com connection strategy: route directly or follow resolver/hosts, and use HTTP or HTTPS.',
    wallhubSteamWebApiRouteLabel: 'Connection route',
    wallhubSteamWebApiRouteDirect: 'Direct',
    wallhubSteamWebApiRouteFollow: 'Follow resolver & hosts',
    wallhubSteamWebApiProtocolLabel: 'Protocol',
    wallhubSteamWebApiHostLabel: 'API host',
    steamCdnLockedByAccessEnhance: 'Steam enhanced access does not lock the HTTP(S)/SOCKS5 proxy setting.',
    dohPickerTitle: 'Resolver selection',
    dohSelectDesc: 'Choose DoH or DoT to resolve Steam domain IPs.',
    dohCurrent: 'Current resolver',
    dohModeFastest: 'Fastest response',
    dohModeFixed: 'Fixed resolver',
    dohSwitch: 'Change',
    dohSave: 'Save resolver',
    resolverPickerTitle: 'Connection mode',
    resolverSelectDesc: 'Switch between Smart Resolver and Hosts. Smart Resolver is best for automatic recovery from DNS pollution, while Hosts is best when you want fixed mappings.',
    resolverModeResolver: 'Smart Resolver',
    resolverModeHosts: 'Hosts mode',
    resolverSelectedCount: 'Selected resolvers',
    resolverCustomEndpoint: 'Custom',
    resolverHostsTitle: 'Hosts mode',
    resolverHostsDesc: 'Hosts mode only uses the persisted local hosts mapping. Missing hosts fall back to the normal access path and do not silently call DoH/DoT.',
    resolverHostsPlaceholder: '此处可以参考https://github.com/gagadog/steam_hosts',
    resolverHostsImport: 'Save hosts',
    resolverHostsFetch: 'Import/refresh',
    resolverHostsUrlPlaceholder: 'https://gh-proxy.org/https://raw.githubusercontent.com/ChEnLeo-7/Github_hosts/refs/heads/main/steam-hosts',
    resolverHostsAutoUpdate: 'Auto-update hosts (hours)',
    resolverHostsLastUpdated: 'Last updated',
    resolverHostsLastError: 'Last error',
    resolverProtocolDoh: 'DoH',
    resolverProtocolDot: 'DoT',
    resolverCurrent: 'Current route',
    resolverModeFastest: 'Fastest response',
    resolverModeFixed: 'Fixed resolver',
    resolverSwitch: 'Manage',
    resolverSave: 'Add resolver',
    steamProxyQuickOpen: 'Open Steam URL through proxy',
    steamProxyQuickOpenDesc: 'Enter a Steam URL and open it through the Wallhub proxy entry. Useful when Steam pages need the built-in connection enhancement.',
    steamProxyQuickOpenPlaceholder: 'https://steamcommunity.com/ or https://store.steampowered.com/',
    steamProxyQuickCommunity: 'Steam Community',
    steamProxyQuickStore: 'Steam Store',
    steamProxyQuickWorkshop: 'Wallpaper Workshop',
    steamProxyQuickCharts: 'Steam charts',
    openProxyUrl: 'Open proxy',
    appearanceIntro: 'Adjust home page density and interface language.',
    language: 'Language',
    languageDesc: 'Switch the frontend display language.',
    accentTheme: 'Theme color',
    accentThemeDesc: 'Switch Monet-style accent colors. Default keeps the black and white mode.',
    accentMono: 'Default mono',
    accentBlue: 'Monet blue',
    accentGreen: 'Monet green',
    accentRose: 'Monet rose',
    accentViolet: 'Monet violet',
    accentCustom: 'Custom',
    customAccentColor: 'Custom theme color',
    fixedPanelHeight: 'Fixed panel height',
    fixedPanelHeightDesc: 'When enabled, secondary panels such as Settings, Queue, Details, and Login use a fixed height and scroll internally.',
    detailsPresentation: 'Details page style',
    detailsPresentationDesc: 'Switch between the original detail layout and the redesigned focused layout.',
    detailsPresentationClassic: 'Classic (original)',
    detailsPresentationRedesigned: 'Redesigned focused layout',
    homePageSize: 'Home cards per page',
    homePageSizeDesc: 'Controls how many cards Wallhub loads and paginates on the home page.',
    homeCardDefaultAction: 'Home card default button',
    homeCardDefaultActionDesc: 'Choose the default action for the button at the bottom of wallpaper cards.',
    actionPlayVideo: 'Play video',
    actionBackgroundDownload: 'Background download',
    actionClientDownload: 'Download locally',
    actionOpenSteamPage: 'Open Steam page',
    remoteSubscribePreparing: 'Sending the subscription request to Steam...',
    remoteSubscribeSuccess: 'Request sent! Check Personal Subscriptions or Wallpaper Engine on your computer',
    remoteSubscribePending: 'Subscribing{dots}',
    remoteSubscriptionActive: 'Subscribed',
    actionUnsubscribe: 'Unsubscribe',
    remoteUnsubscribePreparing: 'Sending the unsubscribe request to Steam...',
    remoteUnsubscribeSuccess: 'Unsubscribe request sent! Refresh Personal Subscriptions to check the result.',
    actionSubscribe: 'Subscribe',
    remoteFavoritePreparing: 'Sending the favorite request to Steam...',
    remoteFavoriteSuccess: 'Favorite request sent! Check My Favorites to see it.',
    remoteFavoritePending: 'Saving favorite{dots}',
    remoteFavoriteActive: 'Favorited',
    actionFavorite: 'Favorite',
    remoteUnfavoritePreparing: 'Sending the remove-favorite request to Steam...',
    remoteUnfavoriteSuccess: 'Remove-favorite request sent! Refresh My Favorites to check the result.',
    actionUnfavorite: 'Remove favorite',
    mobileColumns: 'Mobile home columns',
    desktopColumns: 'Desktop home columns',
    autoFit: 'Auto fit',
    auto: 'Auto',
    enabled: 'Enabled',
    disabled: 'Disabled',
    runtimeReady: 'runtime files ready',
    runtimeReadyJson: 'JSON progress downloader ready',
    runtimeCheckSteamKit: 'Checking SteamKit runtime files',
    runtimeBuildSteamKit: 'Building SteamKit JSON progress downloader',
    runtimeRelogin: 'Please log in to Steam again',
    runtimeLoginRestored: 'restored login',
    runtimeLoginKept: 'kept login',
    runtimeSessionUnverified: 'local login session is not verified, please log in again',
    runtimePrepareFailed: 'runtime preparation failed',
    runtimeBuildFailed: 'SteamKit JSON progress downloader build failed',
    queueEmpty: 'The queue is empty',
    queueStatusFilter: 'Download queue status filters',
    queueTypeFilter: 'Download queue wallpaper type filters',
    queueFilterModeSwitch: 'Switch between status and wallpaper type filters',
    queueFilterAll: 'All',
    queueFilterVideo: 'Video',
    queueFilterScene: 'Scene',
    queueFilterWeb: 'Web',
    queueFilterCompleted: 'Completed',
    queueFilterDownloading: 'Downloading',
    queueFilterPending: 'Queued',
    queueFilterFailed: 'Failed',
    queueFilteredEmpty: 'No tasks match the selected statuses',
    resumeAll: 'Resume all',
    pauseAll: 'Pause all',
    clearCompletedFailed: 'Clear completed and failed',
    waitingRealProgress: 'Downloading, waiting for downloader progress',
    waitingProgress: 'Waiting for progress',
    sizeUnknown: 'Size unknown',
    play: 'Play',
    download: 'Download',
    pause: 'Pause',
    resume: 'Resume',
    moveUp: 'Move up',
    moveDown: 'Move down',
    delete: 'Delete',
    statusPending: 'Queued',
    statusDownloading: 'Downloading',
    statusMoving: 'Moving',
    statusPaused: 'Paused',
    statusError: 'Failed',
    statusCompleted: 'Completed',
    author: 'Author',
    loadingAuthor: 'Loading',
    playVideo: 'Play video',
    backgroundDownload: 'Background download',
    downloadLocal: 'Download locally',
    openSteamPage: 'Open Steam page',
    subscriptions: 'Subscriptions',
    favorites: 'Favorites',
    views: 'Views',
    fileSize: 'File size',
    lastUpdated: 'Last updated',
    type: 'Type',
    loadingDescription: 'Loading description...',
    noDescription: 'No description',
    comments: 'Comments',
    loadingComments: 'Loading comments...',
    noComments: 'No comments',
    genreFilterTitle: 'Genre filter',
    genreTabGenres: 'Genres',
    genreTabOfficial: 'Official filters',
    genreTabResolution: 'Resolution',
    genreActiveFilters: 'Selected filters',
    clear: 'Clear',
    selectAll: 'Select all',
    applyFilter: 'Apply filters',
    steamLoginTitle: 'Steam account login',
    cancel: 'Cancel',
    cancelQr: 'Cancel QR',
    generateQr: 'Generate QR',
    submitGuard: 'Submit code',
    submitSteamToken: 'Log in with token',
    login: 'Log in',
    passwordLogin: 'Password',
    qrLogin: 'QR login',
    qrHelp: 'Scan the QR code with the Steam mobile app. DepotDownloader will save the local session after login succeeds.',
    passwordHelp: 'DepotDownloader verifies the Steam account and saves a local session. The password is not stored.',
    steamUsername: 'Steam username',
    steamPassword: 'Steam password',
    steamGuard: 'Steam Guard code',
    useSteamToken: 'Use Steam token',
    steamTokenCode: 'Steam token code',
    steamTokenHelp: 'Enter the code from Steam Mobile Authenticator to verify directly instead of waiting for email or phone approval.',
    enterSteamToken: 'Enter a Steam token code',
    qrGenerating: 'Generating QR code',
    qrStart: 'Generate a QR code to start login',
    qrWaitImage: 'Generating a scannable QR code...',
    qrWaitingOutput: 'Waiting for DepotDownloader QR output...',
    qrWillShow: 'The QR code will appear here',
    qrConfirmed: 'Confirmed account',
    qrFailed: 'QR login failed',
    enterCredentials: 'Enter username and password',
    guardRequired: 'Steam Guard code required',
    loginFailed: 'Login failed',
    loginStatus: 'Current login status',
    loginStarting: 'Starting login verification',
    phoneConfirmationRequired: 'Confirm this login in the Steam mobile app, then check your phone.',
    prevPage: 'Previous',
    nextPage: 'Next',
    backToTop: 'Back to top',
    loadingWorkshop: 'Fetching Steam Workshop...',
    warmingSteamIp: '正在预热SteamIP……',
    emptyWorkshop: 'No matching wallpapers. Try changing the filters.',
    networkHint: 'The current network may not be able to reach Steam Community. If a proxy is required, make sure the server process can read HTTP_PROXY / HTTPS_PROXY.',
    retry: 'Retry',
    copyProxyDomains: 'Copy proxy domains',
    genres: {
      Abstract: 'Abstract',
      Animal: 'Animal',
      Anime: 'Anime',
      Cartoon: 'Cartoon',
      CGI: 'CGI',
      Cyberpunk: 'Cyberpunk',
      Fantasy: 'Fantasy',
      Game: 'Game',
      Girls: 'Girls',
      Guys: 'Guys',
      Landscape: 'Landscape',
      Medieval: 'Medieval',
      Memes: 'Memes',
      MMD: 'MMD',
      Music: 'Music',
      Nature: 'Nature',
      'Pixel art': 'Pixel art',
      Relaxing: 'Relaxing',
      Retro: 'Retro',
      'Sci-Fi': 'Sci-Fi',
      Sports: 'Sports',
      Technology: 'Technology',
      Television: 'Television',
      Vehicle: 'Vehicle',
      Unspecified: 'Unspecified',
    },
  },
} as const;

export type AppText = (typeof TEXT)[Language];
export type Language = 'zh' | 'en';

export const LanguageContext = React.createContext<{ language: Language; text: AppText }>({
  language: 'zh',
  text: TEXT.zh,
});

export function textFor(language: Language): AppText {
  return language === 'en' ? TEXT.en : TEXT.zh;
}

export function useText() {
  return React.useContext(LanguageContext).text;
}
